Add cloud configuration support for azure client libraries
Azure/azure-sdk pull request #1550
Opened 2020-07-13 19:37 UTC by johanste

Draft PR for gathering feedback on cloud configuration support. Once capabilities are agreed upon, I will create separate PR to update actual guidelines.

2020-09-14 22:31 UTC, lmazuel commented on docs/python/clouddiscover.md
> +In order to discover which endpoints (DNS names and suffixes) are to be used when connecting to a specific cloud, a disovery endpoint has been introduced. This reduces the amount of information a dev
```suggestion
In order to discover which endpoints (DNS names and suffixes) are to be used when connecting to a specific cloud, a discovery endpoint has been introduced. This reduces the amount of information a developer needs in order to connect to a given cloud to knowing a single endpoint.
```

2020-09-14 22:31 UTC, lmazuel commented on docs/python/clouddiscover.md
> +* Allow use of configuration data retreived from cloud configuration discovery endpoint for private cloud instances.
```suggestion
* Allow use of configuration data retrieved from cloud configuration discovery endpoint for private cloud instances.
```

2020-09-14 22:31 UTC, lmazuel commented on docs/python/clouddiscover.md
> +> The cloud configuration instance MAY be represented by a custom type in strongly typed lanugages.
```suggestion
> The cloud configuration instance MAY be represented by a custom type in strongly typed languages.
```

2020-09-14 22:31 UTC, lmazuel commented on docs/python/clouddiscover.md
> +* Ambient default cloud (if supported)
I would expect to to see constructor after "method call", and before "ambient". Or do you mean constructor already? Since I don't think we want to change the endpoint per operation.

2020-09-14 22:31 UTC, lmazuel commented on docs/python/clouddiscover.md
> +* Endpoint specific environment variables (e.g. `AZURE_AUTHORITY_HOST`)
Do we need to list the env variables that are mapping your JSON above? In your table above?

2020-09-14 22:31 UTC, lmazuel commented on docs/python/clouddiscover.md
> +config = CloudConfiguration.from_json(requests.get('https://azurestackinstance1.contoso.com/discover'.json()))
namespace of `CloudConfiguration`? `azure.core.cloud`?

2020-09-14 22:31 UTC, lmazuel commented on docs/python/clouddiscover.md
> +config = CloudConfiguration.from_json(requests.get('https://azurestackinstance1.contoso.com/discover'.json()))
I understand this is just an example, but I would make explicit in your example/guildelines that we need a "get_cloud_endpoint" like [this](https://github.com/Azure/msrestazure-for-python/blob/7986cdcc41d4131e1d6d866e8c80925921e25969/msrestazure/azure_cloud.py#L235) and we're not telling people to do their own requests (but that from_json is important for a file loading scenario).

2020-09-14 22:31 UTC, lmazuel commented on docs/python/clouddiscover.md
> +       "endpoint": "<url>",
Should we have higher metadata format:
```
{
   "name": "AzureChina",
   "services": {
        your JSON data
    },
   "name": "MyStack",
   "services": {
        your JSON data
    }
}
```

2020-09-14 22:31 UTC, lmazuel commented on docs/python/clouddiscover.md
> +* Over time metadata can be added for a given service/new services may be added. Client libraries that depend on the new metadata can set the minimum version of the azure core dependency to ensure th
Should azure.core have a "list_known_cloud" that returns a list of clouds?

2020-09-15 23:00 UTC, jongio commented on docs/python/clouddiscover.md
> +* Endpoint specific environment variables (e.g. `AZURE_AUTHORITY_HOST`)
We also have the AZURE_CLOUD env var that, I believe, is intended to be used as a flag to select a cloud, i.e. AZURE_CLOUD = Gov, then all the gov endpoints would be used by default for the env.

2020-09-21 17:56 UTC, johanste commented on docs/python/clouddiscover.md
> +* Ambient default cloud (if supported)
I did mean constructor. Updated to "parameter provided when creating the client."

2020-09-21 17:59 UTC, johanste commented on docs/python/clouddiscover.md
> +config = CloudConfiguration.from_json(requests.get('https://azurestackinstance1.contoso.com/discover'.json()))
Or `azure.core`. I'm not sure if I'd add another namespace/module just for `CloudConfiguration`.

2020-09-21 18:00 UTC, johanste commented on docs/python/clouddiscover.md
> +config = CloudConfiguration.from_json(requests.get('https://azurestackinstance1.contoso.com/discover'.json()))
I did this intentionally to illustrate that you should be able to use the response from the discovery endpoint as-is. If I used a library method to do this, it would not be clear that it could operate on the exact same schema as the endpoint returns.

2020-09-21 18:04 UTC, johanste commented on docs/python/clouddiscover.md
> +       "endpoint": "<url>",
I assume that you missed an inner array in the example above. Why do you want to have the `"name"` attribute? In general, I try to avoid having arrays-with-objects-that-have-a-unique-key. If you don't, you always have to be on the lookout for duplicate items. I'm not sure if having the name of the configuration item in the object itself has enough value to outweigh the uniqueness problem or the fact that the consumer of the configuration (e.g. the clients) can/will do anything with the value.

2020-09-21 18:35 UTC, johanste commented on docs/python/clouddiscover.md
> +* Over time metadata can be added for a given service/new services may be added. Client libraries that depend on the new metadata can set the minimum version of the azure core dependency to ensure th
Probably. But presumably you know which cloud you are targeting. So the main functionality (I expect) would be to figure out what the programatic name for the cloud you are interested in would be the main use case - and that could probably be solved with documentation.

There are obviously oddball use-cases like the CLI listing clouds. Which is why the API makes sense in the SDK.

2020-09-21 18:45 UTC, johanste commented on docs/python/clouddiscover.md
> +* Endpoint specific environment variables (e.g. `AZURE_AUTHORITY_HOST`)
This interacts in interesting ways with the ambient default cloud. Changed to the following order: Explicitly set (by the application) ambient default cloud > endpoint-specific environment variables > default cloud environment variables.

2021-04-09 22:33 UTC, johanste commented on docs/python/clouddiscover.md
> +config = CloudConfiguration.from_json(requests.get('https://azurestackinstance1.contoso.com/discover'.json()))
Added `azure.core.clouds`.

2021-04-11 21:54 UTC, JonathanGiles commented on docs/python/clouddiscover.md
> +* Service specific client libraries that have baked-in cloud-specific defaults MUST accept a cloud configuration instance in the constructor (or equivalent) for the service client instance. Client li
```suggestion
* Service specific client libraries that have baked-in cloud-specific defaults MUST accept a cloud configuration instance in the constructor (or equivalent) for the service client instance. Client libraries MAY also accept a simple cloud name.
```

2021-04-11 21:54 UTC, JonathanGiles commented on docs/python/clouddiscover.md
> +None of then individual properties in a service configuration entry are required as they differ between different services (e.g. a service can have a well-known endpoint or a suffix, but it never has
```suggestion
None of the individual properties in a service configuration entry are required as they differ between different services (e.g. a service can have a well-known endpoint or a suffix, but it never has both)
```

2021-04-11 21:54 UTC, JonathanGiles commented on docs/python/clouddiscover.md
> +* Final fallback, corresponding Public Azure's settings (built in to the client library)
Just confirming: is this final bullet point referring to the various 'endpoint' APIs we have in our constructors / builders today?

2021-04-11 21:54 UTC, JonathanGiles commented on docs/python/clouddiscover.md
> +* Adding a new required configuration property for a given method/API is a breaking change.
I'm having trouble on these two points. I read above that configuration was passed in at construction of the service client. I don't know how these two points above relate to that - in what context is there a method that accepts a configuration object, or are you talking about validating the configuration at service client instantiation time?

2021-04-12 17:51 UTC, m-nash commented
Should we also consider "Well known locations" as either a property of a "Well known cloud" or as a standalone set?  Example: https://github.com/Azure/azure-sdk-for-net/blob/feature/mgmt-track2/sdk/resourcemanager/Azure.ResourceManager.Core/src/Resources/LocationData.cs#L37.

This list would follow the same principal of customers should be able to make custom locations for private cloud scenarios.

2021-04-12 17:55 UTC, johanste commented
> Should we also consider "Well known locations" as either a property of a "Well known cloud" or as a standalone set? Example: https://github.com/Azure/azure-sdk-for-net/blob/feature/mgmt-track2/sdk/resourcemanager/Azure.ResourceManager.Core/src/Resources/LocationData.cs#L37.
> 
> This list would follow the same principal of customers should be able to make custom locations for private cloud scenarios.

It is a good question, and I've been thinking if we should add support for additional properties under a "service entry" in the configuration. For the locations defined in the LocationData above, it is really a well-known property for a specific service (ARM). It does not translate clearly to other services, although ARM locations in particular do sometimes bleed out to other services given that it represents locations where data centers are available.

2021-04-12 17:57 UTC, m-nash commented
> > Should we also consider "Well known locations" as either a property of a "Well known cloud" or as a standalone set? Example: https://github.com/Azure/azure-sdk-for-net/blob/feature/mgmt-track2/sdk/resourcemanager/Azure.ResourceManager.Core/src/Resources/LocationData.cs#L37.
> > This list would follow the same principal of customers should be able to make custom locations for private cloud scenarios.
> 
> It is a good question, and I've been thinking if we should add support for additional properties under a "service entry" in the configuration. For the locations defined in the LocationData above, it is really a well-known property for a specific service (ARM). It does not translate clearly to other services, although ARM locations in particular do sometimes bleed out to other services given that it represents locations where data centers are available.

Agreed, having it in Azure.ResourceManager.Core is fine by me vs Azure.Core for that reason, but I am wondering if any centralization across languages can / should

2021-04-12 18:17 UTC, weshaggard commented on docs/python/clouddiscover.md
> +|Property|Description|Example|
Would it also be interesting to specific the api version supported by this service endpoint?

2021-04-12 18:20 UTC, weshaggard commented on docs/python/clouddiscover.md
> +* Endpoint specific environment variables (e.g. `AZURE_AUTHORITY_HOST`)
If not the specific env variable perhaps we can provide a well known pattern for property to env variable name so that we can start to have consistency in how they env variables are named.

2021-04-12 18:25 UTC, johanste commented on docs/python/clouddiscover.md
> +|Property|Description|Example|
My intent is to not include information that is changing over time into the configuration. Encoding the "current state of the cloud" adds a bunch of complications (e.g. stuff gets out of date over time - especially when clients have serialized the configuration data in to local storage).

This information is currently not exposed by the metadata endpoint. So unless it gets added there, loading the configuration from the metadata endpoint would not be able to make it available. The official REST API guidelines state that all services should support HTTP `OPTIONS` requests to query what API versions are available - however, I'm not sure how many (if any) services actually support this correctly. 

@weshaggard, what scenario would you want to light up using this information? I can see two different use cases; know what API version the cloud supports and client applications wanting to specify which API version to use by default for a given service....

2021-04-12 18:29 UTC, johanste commented on docs/python/clouddiscover.md
> +* Endpoint specific environment variables (e.g. `AZURE_AUTHORITY_HOST`)
We have a [list of "well known" environment variables](https://azure.github.io/azure-sdk/general_azurecore.html) in the general design guidelines. Regarding naming, it only includes the requirement that they are prefixed with `AZURE_`. Should we have more specific guidance?

2021-04-12 18:32 UTC, weshaggard commented on docs/python/clouddiscover.md
> +* Endpoint specific environment variables (e.g. `AZURE_AUTHORITY_HOST`)
It would be nice if there was more guidance around how those look so that we have consistency but I suppose we have to wait and see what patterns emerge to create such a guideline.

2021-04-12 18:35 UTC, johanste commented on docs/python/clouddiscover.md
> +* Endpoint specific environment variables (e.g. `AZURE_AUTHORITY_HOST`)
Just an observation; we had a flurry of variables getting added early on, but the list hasn't grown much since then.

2021-04-12 18:41 UTC, weshaggard commented on docs/python/clouddiscover.md
> +|Property|Description|Example|
I was mostly thinking about how our client libraries default to the latest api version and depending on what cloud they connect to that might cause problems if the cloud doesn't support that version. So customers that are specifying a cloud configuration may be required to first figure out and then specify the correct version. What is worse is that they will need to manually maintain that version overtime as well. All that seems like a recipe for errors that it would be great if we could come up with some way to query the information. 

I know this is a bigger problem and there are other issues like https://github.com/Azure/azure-sdk/issues/1198 discussing this but at the very least these guidelines should provide guidance for how folks should get the versions. I guess I was somewhat hoping this configuration service you are referring too was still being developed and if so then we could somehow pull in the versions with it.

2021-04-12 18:42 UTC, johanste commented on docs/python/clouddiscover.md
> +* Final fallback, corresponding Public Azure's settings (built in to the client library)
Yes. Is there any way I can rephrase to make it more clear?

2021-04-12 18:50 UTC, johanste commented on docs/python/clouddiscover.md
> +|Property|Description|Example|
Ah, for that, there is a separate construct (API profiles) that clouds are supposed to expose: https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles?view=azs-2008.

Additionally, service instances should include which API version they support when rejecting a call. So, while it may not be pretty, assuming that the client library supports multiple API versions, it is relatively straight-forward to adjust while trying things out. What historically was a pain for single-api-version packages was to try to map the API version to the corresponding library version.

I would *not* expect clients to dynamically pull the API version and adjust according to what the cloud supports other than for very specific applications that are designed to dynamically change its behavior based on the target cloud capabilities. This is rare. And you would almost always have to put a "ceiling" on which API versions you support since there is no guarantee that the new update that was deployed overnight on the cloud instance that you are targeting didn't break your application in a more or less subtle way.

2021-04-12 18:53 UTC, weshaggard commented on docs/python/clouddiscover.md
> +|Property|Description|Example|
Ok I do still think it is at least worth calling out in these guidelines what the expectation is around picking the correct versions.

2021-04-12 19:01 UTC, markcowl requested changes

2021-04-12 19:01 UTC, markcowl commented on docs/python/clouddiscover.md
> +azure.core.settings.cloud_configuration = azure.core.clouds.well_known['AzureChinaCloud']
in this instance, does authority and other authentication settings come from the cloud configuration?

2021-04-12 19:12 UTC, markcowl commented on docs/python/clouddiscover.md
> +from azure.core.clouds import CloudConfiguration
Also, I think we should have guidance and example  around the actual endpoint metadata discovery protocol.  There is a JEDI requirement that we use a single endpoint for discovering available endpoint metadata.  Would be nice to see this, and also, a sample of using discovery metadata to populate a configuration object.

2021-04-12 19:25 UTC, johanste commented on docs/python/clouddiscover.md
> +    "endpoint": "<url>",
I assume you mean `ADFS` vs `AAD`?

2021-04-12 19:26 UTC, johanste commented on docs/python/clouddiscover.md
> +azure.core.settings.cloud_configuration = azure.core.clouds.well_known['AzureChinaCloud']
Yes.

2021-04-12 19:36 UTC, johanste commented on docs/python/clouddiscover.md
> +from azure.core.clouds import CloudConfiguration
```python
config: typing.Mapping[str, CloudConfiguration] = {
   data['name']: CloudConfiguration.from_metadata_dict(data)
   for data in requests.get('https://azurestackinstance1.contoso.com/discover?api-version=2019-05-01'.json()
 }
```

is an example on how to load from a cloud instance's metadata endpoint (although I realize that the example is using the wrong endpoint URL - I have update this).

2021-04-12 19:37 UTC, johanste commented on docs/python/clouddiscover.md
> +azure.core.settings.cloud_configuration = azure.core.clouds.well_known['AzureChinaCloud']
More specifically, from the `global` section of the configuration.

2021-04-12 19:40 UTC, johanste commented on docs/python/clouddiscover.md
> +* Change in requirements for client libraries to always accept a simple name (e.g. storage account name) in addition to full endpoint information when constructing clients.
Not based on the requirements outlined in this document, no. I don't think sovereign/alternate cloud configurations introduces any new requirement than those we had when the general guidelines to require full endpoints were decided upon.

Do you think it should?

2021-04-12 19:41 UTC, johanste commented on docs/python/clouddiscover.md
> +* Well-known (public) cloud configurations MUST be built-in to the client libraries for each language. Each well-known cloud configuration has a "simple name" in addition to a set of key/value pairs
Yes. I originally had the auth endpoints per service. But after talking to @schaabs  and @chlowell, I moved them to a single "global" section. I'm not entirely happy with the name `global`, however, so any suggestions on what to rename it to would be very appreciated.

2021-04-20 16:34 UTC, KrzysztofCwalina reviewed
At a high level, I have two main concerns about the plan:
1. The cost of implementing and testing it will be very high. Should we start small, i.e. less knobs and a subset of services.
2. I would like to design the APIs such that we don't end up with bunch of legacy APIs in a couple of years. It seems to me like some of these APIs have the potential of aging worse than the main APIs in corresponding libraries.

2021-04-20 16:34 UTC, KrzysztofCwalina commented on docs/python/clouddiscover.md
> +* Change in requirements for client libraries to always accept a simple name (e.g. storage account name) in addition to full endpoint information when constructing clients.
I would prefer for this to be an option on client options, not a requirement, though I might be misinterpreting what you mean by "always".

2021-04-20 16:34 UTC, KrzysztofCwalina commented on docs/python/clouddiscover.md
> +* Well-known (public) cloud configurations MUST be built-in to the client libraries for each language. Each well-known cloud configuration has a "simple name" in addition to a set of key/value pairs
What are the keys and what are the values in these KVPs?

2021-04-20 16:34 UTC, KrzysztofCwalina commented on docs/python/clouddiscover.md
> +> The simple cloud name MAY be a string or an enum value.
Why? It seems like some of the requirements below have too much detail. For example, I can imagine cloud names being properties in .NET, e.g. Cloud.Governemt.Enable = true;

2021-04-20 16:34 UTC, KrzysztofCwalina commented on docs/python/clouddiscover.md
> +* The core library MUST provide a mechanism to list well-known cloud instance names.
What's the scenario for listing them?

2021-04-20 16:34 UTC, KrzysztofCwalina commented on docs/python/clouddiscover.md
> +* It MUST be possible (and documented how) to load a configuration from the returned information in ARM's discovery endpoint. Unknown configuration data retrieved from the ARM discovery endpoint (e.g
Could you point to REST API docs for this endpoint? I tried to search it and was not clear which API it is.

2021-04-20 16:34 UTC, KrzysztofCwalina commented on docs/python/clouddiscover.md
> +|Property|Description|Example|
Since we will be adding APIs to Azure Core, maybe we add an API to override the default API version. This would be more convenient than chasing every single client instance. 

Also, we need to think how that would work for reusable libraries.

2021-04-20 16:34 UTC, KrzysztofCwalina commented on docs/python/clouddiscover.md
> +* Final fallback, corresponding Public Azure's settings (built in to the client library)
Would it be reasonable to start with simple chain? client setting > global setting > default

2021-04-20 16:34 UTC, KrzysztofCwalina commented on docs/python/clouddiscover.md
> +* Methods that accept a configuration object that is missing one or more configuration settings that it expects MUST raise an error. The error message MUST be clear enough for the developer to unders
How are we going to develop it and test it? Seems like it would be very expensive. Maybe LLC is the answer here, i..e when call fails, the users needs to modify the request.

2021-04-20 16:34 UTC, KrzysztofCwalina commented on docs/python/clouddiscover.md
> +```
It's not clear to me why we offer so many options. Is there a reason besides that we can?

2021-04-20 17:59 UTC, johanste commented on docs/python/clouddiscover.md
> +|Property|Description|Example|
My opinion: we should allow user to specify the profile they want to use at a global/default level. This is related to but not exactly the same as configuring which cloud to use. 

Reusable libraries should still be explicit about the API version used (for internal usage/they need to understand the response) or omit it (if they are just transparently passing data around/use the types from the library as exchange types).

2021-04-20 17:59 UTC, johanste commented on docs/python/clouddiscover.md
> +|`graph`||
Which library is using the gallery endpoint?

2021-04-20 18:01 UTC, johanste commented on docs/python/clouddiscover.md
> +* Change in requirements for client libraries to always accept a simple name (e.g. storage account name) in addition to full endpoint information when constructing clients.
My intent was to specify that the addition of cloud configurations does not change any requirements to take simple names in addition to full URLs from before. Any service that requires a full URL/endpoint to day will continue to require the user specify a full URL/endpoint.

2021-04-20 18:03 UTC, johanste commented on docs/python/clouddiscover.md
> +* Final fallback, corresponding Public Azure's settings (built in to the client library)
This is more or less what I have here - with the only twist that we *already* have bespoke environment variables for some settings (e.g. `AZURE_AUTHORITY_HOST`)

2021-04-20 18:03 UTC, johanste commented on docs/python/clouddiscover.md
> +* Methods that accept a configuration object that is missing one or more configuration settings that it expects MUST raise an error. The error message MUST be clear enough for the developer to unders
Nah, look in the configuration passed in and raise an exception if something you needed isn't available.

2021-04-20 18:07 UTC, johanste commented on docs/python/clouddiscover.md
> +> The simple cloud name MAY be a string or an enum value.
I can reduce the requirements if there are other ways to accomplish the same task. 

There is a hard requirement to support clouds other than well known clouds. Azure stack is one example. Whatever solution you have would have to support a developer to be able to target two separate stack instances from a single application.

2021-04-20 18:08 UTC, johanste commented on docs/python/clouddiscover.md
> +* The core library MUST provide a mechanism to list well-known cloud instance names.
Both powershell and the CLI needs those capabilities. As would presumably other management tools.

2021-04-20 18:16 UTC, johanste commented on docs/python/clouddiscover.md
> +* It MUST be possible (and documented how) to load a configuration from the returned information in ARM's discovery endpoint. Unknown configuration data retrieved from the ARM discovery endpoint (e.g
I will try to find the public documentation. I used the internal docs when I wrote the proposal :). The endpoint is there in public azure, but I'm not sure if our docs pages render it correctly (it doesn't follow the standard API pattern for ARM)

2021-04-20 20:05 UTC, tg-msft reviewed
This looks great.

2021-04-20 20:05 UTC, tg-msft commented on docs/python/clouddiscover.md
> +azure.core.settings.cloud_configuration = 'AzureChinaCloud'
Does this value stay a string in this case?  It'd be nice if this had all the properties of my current cloud if I wanted to write something really generic that lit up based on the current environment.  (I know that's half of a non-goal, but if you're creating somewhere global state can hang I think that's how people will use it.)

2021-04-20 20:05 UTC, tg-msft commented on docs/python/clouddiscover.md
> +}
Why doesn't CloudConfiguration have something that just takes the URI instead of making everyone write a dict comprehension?  Or this logic not general purpose in some important way?

2021-04-20 20:05 UTC, tg-msft commented on docs/python/clouddiscover.md
> +* Explicitly provided configuration value from cloud_configuration parameter provided when creating the client.
What about non cloud-config values specified on a client?  In other words, if someone specifies half of what's necessary to instantiate a client, do we pull the other half from cloud-config settings in this order?

2021-04-20 20:22 UTC, tg-msft commented on docs/python/clouddiscover.md
> +
I tried to very roughly translate that to a first guess at how I could imagine C# looking:

```C#
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager.Compute;

// In order to default to switch all default values to match the expected configuration for
// the Azure China Cloud.
AzureConfiguration.Default = AzureConfiguration.AzureChinaCloud; // or AzureConfiguration["AzureChinaCloud"];

// We will use the Azure China Cloud's authority (https://login.chinacloudapi.cn) since that is what is configured as the default cloud.
var creds = new DefaultAzureCredential();

// The default management endpoint from AzureChinaCloud is used
// (picked up from the resourceManager service entry in of the AzureChinaCloud built-in cloud configuration)
var client = new ComputeManagementClient(subscriptionId, creds)

// I can still specify the default authority host to override the default settings...
var options = new DefaultAzureCredentialOptions { AuthorityHost = new Uri("https://login.windows.net") };
var publicAzureCreds = new DefaultAzureCredential(options);

// I can also specify a full cloud configuration object:
// In order to default to switch all default values to match the expected configuration for
// the Azure China Cloud.
AzureConfiguration.Default = AzureConfiguration.AzureChinaCloud; // or AzureConfiguration["AzureChinaCloud"];

// ...or pass in a custom cloud configuration instance into a method
var config = await AzureConfiguration.GetAsync(new Uri("https://azurestackinstance1.contoso.com/discover?api-version=2019-05-01"));
options = new DefaultAzureCredentialOptions { AzureConfiguration = config["AzureStackInstance1"] };
creds = new DefaultAzureCredential(options);

// ...or by name
options = new DefaultAzureCredentialOptions { AzureConfiguration = AzureConfiguration.AzurePublicCloud };
creds = new DefaultAzureCredential(options);
```

2021-04-20 22:10 UTC, johanste commented on docs/python/clouddiscover.md
> +There are multiple Azure Cloud instances. This includes well-known cloud instances such as Public Azure, Azure China Cloud, Azure Government Cloud etc. It also includes private cloud instances that a
Need to talk to @schaabs about how to possibly plumb auth through from config.

2021-04-20 22:22 UTC, johanste commented on docs/python/clouddiscover.md
> +for known_cloud in azure.core.clouds.well_known:
Baked into azure core.

2021-04-20 22:45 UTC, johanste commented on docs/python/clouddiscover.md
> +> Examples of cloud specific defaults include hostnames (for services sharing a common DNS name, such as ARM) and host name suffixes (for client libraries that concatenate a "simple" service name wit
Yes. We should add an optional scopes to the configuration schema.

2021-04-20 22:48 UTC, johanste commented on docs/python/clouddiscover.md
> +* Explicitly provided configuration value from cloud_configuration parameter provided when creating the client.
Yes.

2021-04-20 23:20 UTC, lilyjma commented
[Recording](https://msit.microsoftstream.com/video/32d70840-98dc-94b1-b4dc-f1eba22cd02d)[MS INTERNAL ONLY]

2021-06-21 21:50 UTC, jongio requested changes

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +* Simplify configuring for a client connecting to public clouds other than Public Azure.
```suggestion
* Simplify configuring for a client connecting to clouds other than Public Azure.
```

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +In order to discover which endpoints (DNS names and suffixes) are to be used when connecting to a specific cloud, a discovery endpoint has been introduced. This reduces the amount of information a de
```suggestion
To discover which endpoints (DNS names and suffixes) are to be used when connecting to a specific cloud, a discovery endpoint will be introduced. This reduces the amount of information a developer needs to connect to a given cloud to knowing a single endpoint.
```

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +* Automatically discover which cloud an application runs in and default libraries to use that by default.
```suggestion
* Automatically discover which cloud an application runs in and set that as a default for libraries to use.
```

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +* Automatically discover which cloud an application runs in and default libraries to use that by default.
Because you put this as a non-goal I had to think about why that would be a non-goal, but I can see it being useful.

For example, when I new up DefaultAzureCredential it would be nice if it detected what cloud I'm running in and use the appropriate authority host.  Or, if we can't do that because of state or perf, then it would be nice to pass a config object by name to Options, like we can with Fluent today.

`var options = new TokenCredentialOptions{ Cloud = Azure.Gov };`

And that sets context for that options object.

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +* Well-known (public) cloud configurations MUST be built-in to the client libraries for each language. Each well-known cloud configuration has a "simple name" in addition to a set of key/value pairs
Ideally they follow the same pattern and names as what is returned by Azure CLI / PSH, az cloud list.

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +* It MUST be possible (and documented how) to load a configuration from the returned information in ARM's discovery endpoint. Unknown configuration data retrieved from the ARM discovery endpoint (e.g
this is how you register a cloud:
https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest#az_cloud_register


REST ENDPOINT https://management.azure.com/metadata/endpoints?api-version=2019-05-01

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +where `<service entry>` is (currently) one of the following values:
I don't think it is a 1:1 URL:RP mapping, but I do like the idea of being able to map these via some well known static string like RP name.

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +Given that more configuration settings can be added over time, you may run into a situation where not all configuration settings that a client library needs are populated in a provided cloud configur
It would be great to have a fall back mechanism.  

i.e., if we don't find the value, then use the user supplied default.

var endpoint = getendpoint("KEY", "default endpoint")

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +> The simple cloud name MAY be a string or an enum value.
I believe that by introducing the enum version of this we are required to include the clause below about changes being breaking changes.

As much as I like enums, do we want to not do enums so that the config bag can be more flexible and not require a breaking change to change it?

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +* Simplify configuring for a client connecting to public clouds other than Public Azure.
The reason I suggestion removing 'public' is because I believe this helps not just public, but all clouds.

2021-06-21 21:50 UTC, jongio commented on docs/python/clouddiscover.md
> +* Automatically discover which cloud an application runs in and default libraries to use that by default.
Comment after reading whole doc:

You mention below that defaults are set by globals.  I think it would be helpful to clarify the difference between what you are saying above and below.

https://github.com/Azure/azure-sdk/pull/1550/files#diff-d7561b23069d83b9178f5d3d15fb8b6f2d4c69305a7f5bde1eea91e521a9717eR163

2021-07-06 17:01 UTC, johanste commented on docs/python/clouddiscover.md
> +* Adding a new required configuration property for a given method/API is a breaking change.
In this context, the constructor is a "method" (or it can be a factory method). Or, for languages that support module level methods etc (e.g. Python), a module level helper methods. In other words, in practical terms, this is most commonly going to apply to construction of clients, but it also can apply to anything that, internally, creates a service client instance.

2021-07-06 17:02 UTC, johanste commented on docs/python/clouddiscover.md
> +|Property|Description|Example|
Version numbers should not be baked into the host.

2021-07-06 17:03 UTC, johanste commented on docs/python/clouddiscover.md
> +* Well-known (public) cloud configurations MUST be built-in to the client libraries for each language. Each well-known cloud configuration has a "simple name" in addition to a set of key/value pairs
The problem with `az cloud list` is that it is very random in the structure of what it returns.

2021-07-06 17:29 UTC, johanste commented on docs/python/clouddiscover.md
> +```
It is a common practice in Python to "overload" methods that take "well-known instance with name in addition to custom instances" to, accept the name.

2022-03-09 18:30 UTC, lilyjma commented
Arch Board meeting scheduled for 3/17 2-4pm pst

2022-03-17 23:24 UTC, tg-msft commented
[Recording](https://msit.microsoftstream.com/video/65b20840-98dc-997d-6e22-f1eca647b969) (MS INTERNAL ONLY)

2023-06-21 22:04 UTC, johanste commented on docs/python/clouddiscover.md
> +}
The main reason is that I don't trust the evolution of this API. It wasn't as much designed as it grew out of necessity.

2023-08-25 14:04 UTC, johanste commented
Keeping it open

2023-11-24 08:34 UTC, closed without merging