September release notes
Azure/azure-sdk pull request #1818
Opened 2020-09-17 18:25 UTC by RickWinter

Add September release notes for Embedded C
Add September release notes for C++

2020-09-18 03:36 UTC, weshaggard commented on releases/2020-09/c.md
> +---
Don't you also want to add links in the index.md for Sept?

2020-09-18 22:07 UTC, RickWinter commented on releases/2020-09/c.md
> +---
Yes, I don't know all the ins/outs.  I'll make that update and push it to this PR

2020-09-18 23:54 UTC, weshaggard commented on releases/2020-09/c.md
> +---
Should just need to add it to https://github.com/Azure/azure-sdk/blob/master/releases/2020-09/index.md.

2020-09-19 00:21 UTC, weshaggard approved these changes

2020-09-19 01:05 UTC, jongio requested changes

2020-09-19 01:05 UTC, jongio commented on releases/2020-09/c.md
> +title: Azure SDK for Embedded C (September 2020)
Change to October 2020

2020-09-19 01:05 UTC, jongio commented on releases/2020-09/c.md
> +---
Put files under 2020-10

2020-09-19 01:05 UTC, jongio commented on releases/2020-09/c.md
> +The Azure SDK team is pleased to make available the September 2020 client library release.
Change to October

2020-09-21 19:43 UTC, RickWinter commented on releases/2020-09/c.md
> +$>  git clone https://github.com/Azure/azure-sdk-for-c
removed

2020-09-21 19:48 UTC, RickWinter commented on releases/2020-09/c.md
> +Detailed changelogs are linked from the [Quick Links](#quick-links) below. Here are some of the highlights:
I mirrored this based on the other languages.  It's not clear where these go based on the repo, but every language has it

2020-09-22 16:23 UTC, RickWinter commented
@jongio Can you review the updates.

2020-09-22 16:33 UTC, jongio submitted a review, later dismissed

2020-09-22 16:33 UTC, jongio commented on releases/2020-09/c.md
> +Detailed changelogs are linked from the [Quick Links](#quick-links) below. Here are some of the highlights:
Remove as the #quick-links doesn't exist.  Please show me where this is in other langs as it was supposed to be removed.

2020-09-22 16:33 UTC, jongio commented on releases/2020-09/cpp.md
> +Detailed changelogs are linked from the [Quick Links](#quick-links) below. Here are some of the highlights:
Same

2020-09-22 17:29 UTC, ahsonkhan requested changes
I think we should have a "fresh" GA-only based changelog, since we don't have a previous release not for previews as baseline to compare against.

2020-09-22 17:29 UTC, ahsonkhan commented on releases/2020-09/c.md
> +git checkout <tag_name>
Should we just specify the tag name here?

```suggestion
git checkout 1.0.0
```

2020-09-22 17:29 UTC, ahsonkhan commented on releases/2020-09/c.md
> +If you have a bug or feature request for one of the libraries, please post an issue to [GitHub](https://github.com/azure/azure-sdk-for-c/issues).
```suggestion
If you have a bug or feature request for one of the libraries, please post an issue to [GitHub](https://github.com/Azure/azure-sdk-for-c/issues/new/choose).
```

2020-09-22 17:29 UTC, ahsonkhan commented on releases/2020-09/c.md
> +#### Breaking Changes
Since this is our first GA release, I don't think we should have a breaking changes section, which were ephemeral between preview versions.

2020-09-22 17:29 UTC, ahsonkhan commented on releases/2020-09/c.md
> +#### New Features
Similarly, here, I think we should just summarize what features are coming as part of 1.0.0. release, at a high level.

**Something like:**
Azure Core APIs - span, logging, HTTP policies, JSON reader, writer, result, etc.
IoT Hub and Provisioning clients ...

2020-09-22 17:29 UTC, ahsonkhan commented on releases/2020-09/c.md
> +- Add support for building the SDK on ARM (Cortex M4) and adding it to CI.
Similarly here, if we don't have any previous release notes to compare to, and this is our first, for GA, we don't need these sections.

2020-09-22 17:29 UTC, ahsonkhan commented on releases/2020-09/c.md
> +- Azure IoT
What's the purpose of this section?

2020-09-22 18:12 UTC, JeffreyRichter approved these changes

2020-09-22 18:26 UTC, RickWinter commented on releases/2020-09/c.md
> +#### Breaking Changes
The september notes are not about GA.  The October notes will declare the GA

2020-09-22 18:27 UTC, RickWinter commented on releases/2020-09/c.md
> +git checkout <tag_name>
The September notes are not about GA.  These notes are about what we released in September.  

The GA notes will declare the GA.

2020-09-22 18:28 UTC, RickWinter commented on releases/2020-09/c.md
> +- Add support for building the SDK on ARM (Cortex M4) and adding it to CI.
This is not about GA, these notes are in reference to what we released as part of September.  The GA notes will come in October

2020-09-22 18:42 UTC, RickWinter commented on releases/2020-09/cpp.md
> +Detailed changelogs are linked from the [Quick Links](#quick-links) below. Here are some of the highlights:
Ok I'll rip it out.
dotnet.md and python.md have those lines

2020-09-22 18:47 UTC, RickWinter commented on releases/2020-09/c.md
> +If you have a bug or feature request for one of the libraries, please post an issue to [GitHub](https://github.com/azure/azure-sdk-for-c/issues).
We don't link to the new b/c ideally individuals will scan for an existing issue first.

2020-09-22 18:48 UTC, RickWinter commented on releases/2020-09/c.md
> +#### New Features
These notes are in reference to the Beta we did in september and not the GA which will be declared as part of the October release.

2020-09-22 19:39 UTC, ahsonkhan commented on releases/2020-09/c.md
> +If you have a bug or feature request for one of the libraries, please post an issue to [GitHub](https://github.com/azure/azure-sdk-for-c/issues).
OK.

nit:
```suggestion
If you have a bug or feature request for one of the libraries, please post an issue to [GitHub](https://github.com/Azure/azure-sdk-for-c/issues).
```

2020-09-22 19:40 UTC, ahsonkhan commented on releases/2020-09/c.md
> +#### Breaking Changes
In that case, maybe we should add more of the previous changelog info too.

2020-09-22 19:41 UTC, ahsonkhan approved these changes

2020-09-22 21:31 UTC, RickWinter commented on releases/2020-09/c.md
> +#### Breaking Changes
The release notes are specific to the version of the release.  For the previous releases where we didn't incorporate releases the user can access the CHANGELOG.md

2020-09-22 21:35 UTC, RickWinter commented on releases/2020-09/c.md
> +- Azure IoT
Its a list of packages that are changing state in some fashion.  An entry in GA is the package releasing GA.  An entry in Beta is a package that released a new beta,

2020-09-22 21:39 UTC, RickWinter commented
@jongio I removed the quick-links and updated the templates as well.

2020-09-28 16:53 UTC, RickWinter commented
@czubair Can you review.  I'd like to get this checked in today

2020-09-28 16:57 UTC, czubair commented on releases/2020-09/c.md
> +#### New Features
I would change "New Features" to h3 (###). Same with 'Breaking Changes'.

2020-09-28 16:57 UTC, czubair commented on releases/2020-09/c.md
> +
Are all of these critical changes that developers need to know?

2020-09-28 16:57 UTC, czubair approved these changes

2020-09-29 15:24 UTC, RickWinter commented on releases/2020-09/c.md
> +
Is there a bar we should follow for breaking changes in Betas?  Historically we've tried to list everything

2020-09-29 15:25 UTC, merged

2020-09-29 20:35 UTC, ahsonkhan commented on releases/2020-09/c.md
> +#### New Features
These should be h3 matching the other headings: `### Bug Fixes` and `### Other Changes and Improvements`.

Alternatively, mark all of them h4. Right now these headings mismatch results in odd structure.

```suggestion
### New Features
```

![image](https://user-images.githubusercontent.com/6527137/94612846-8b288c00-0258-11eb-8d81-08cb8af8cb20.png)

2020-09-29 20:35 UTC, ahsonkhan commented on releases/2020-09/c.md
> +#### Breaking Changes
```suggestion
### Breaking Changes
```

2020-09-29 20:43 UTC, ahsonkhan commented on releases/2020-09/c.md
> +#### New Features
Resolved in https://github.com/Azure/azure-sdk/pull/1872