[JS] October release notes
Azure/azure-sdk pull request #1878
Opened 2020-09-30 22:34 UTC by sadasant

October release notes for JavaScript.

Please suggest changes with your release notes.

If you're looking for inspiration, the PR for the September release was: https://github.com/Azure/azure-sdk/pull/1750

2020-10-06 18:03 UTC, jeremymeng commented on releases/2020-10/js.md
> +- _REMEMBER TO ADD YOUR BETA PACKAGES_
```suggestion
- Azure Metrics Advisor
- _REMEMBER TO ADD YOUR BETA PACKAGES_
```

2020-10-06 18:04 UTC, jeremymeng commented on releases/2020-10/js.md
> +$> npm install @azure/identity@next
```suggestion
$> npm install @azure/identity@next
$> npm install @azure/ai-metrics-advisor
```

2020-10-06 18:31 UTC, jeremymeng commented on releases/2020-10/js.md
> +### Azure Identity
```suggestion
### Azure Metrics Advisor

#### @azure/ai-metrics-advisor [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md)

(leave blank)

- This is the inital preview of client library that supports the newly announced preview of the Azure Metrics Advisor service.
- This library has been designed based on the [Azure SDK Design Guidelines for TypeScript]({{ site.baseurl }}{% link docs/typescript/introduction.md %}) to ensure consistency, idiomat\
ic design, and excellent developer experience and productivity.
- it supports all services APIs, including but not limited to
  - Manage data feeds
  - Configure anomaly detection and alerting configurations
  - Query anomaly detection results, for example, incidents, anomalies, alerts, enriched series data, etc.
  - Diagnose incident root causes

### Azure Identity
```

2020-10-06 21:30 UTC, joheredi commented on releases/2020-10/js.md
> +
```suggestion
### Azure Tables

#### @azure/data-tables [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/tables/data-tables/CHANGELOG.md)

##### New Features on @azure/data-tables@1.0.0-beta.2

- Implemented batch operations

```

2020-10-06 21:33 UTC, joheredi commented on releases/2020-10/js.md
> +- _REMEMBER TO ADD YOUR BETA PACKAGES_
```suggestion
- Azure Tables

- _REMEMBER TO ADD YOUR BETA PACKAGES_
```

2020-10-06 21:34 UTC, joheredi commented on releases/2020-10/js.md
> +$> npm install @azure/identity@next
```suggestion
$> npm install @azure/identity@next
$> npm install @azure/data-tables@next
```

2020-10-07 23:23 UTC, sadasant commented on releases/2020-10/js.md
> +- This library has been designed based on the [Azure SDK Design Guidelines for TypeScript]({{ site.baseurl }}{% link docs/typescript/introduction.md %}) to ensure consistency, idiomat\
@jeremymeng is this format here right? It looks really weird.

2020-10-07 23:24 UTC, sadasant commented on releases/2020-10/js.md
> +- This library has been designed based on the [Azure SDK Design Guidelines for TypeScript]({{ site.baseurl }}{% link docs/typescript/introduction.md %}) to ensure consistency, idiomatic design, and e
@jeremymeng is this link format ok? it looks really weird.

2020-10-07 23:25 UTC, sadasant commented on releases/2020-10/js.md
> +- Implemented batch operations.
@joheredi can you elaborate?

2020-10-07 23:33 UTC, jeremymeng commented on releases/2020-10/js.md
> +- This library has been designed based on the [Azure SDK Design Guidelines for TypeScript]({{ site.baseurl }}{% link docs/typescript/introduction.md %}) to ensure consistency, idiomatic design, and e
I believe I copied it from one of the existing js.md file.

2020-10-07 23:51 UTC, richardpark-msft reviewed
Adding in @azure/service-bus@7.0.0-preview.7!

2020-10-07 23:51 UTC, richardpark-msft commented on releases/2020-10/js.md
> +
```suggestion
Azure Service Bus
```

2020-10-07 23:51 UTC, richardpark-msft commented on releases/2020-10/js.md
>  ### _Package name_
```suggestion
#### @azure/service-bus@7.0.0-preview.7 [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/CHANGELOG.md)

##### New Features on @azure/service-bus@7.0.0-preview.7

- Message locks can be auto-renewed in all receive methods (receiver.receiveMessages, receiver.subcribe
  and receiver.getMessageIterator). This can be configured in options when calling `ServiceBusClient.createReceiver()`.
  [PR 11658](https://github.com/Azure/azure-sdk-for-js/pull/11658)
- `ServiceBusClient` now supports authentication with AAD credentials in the browser(can use `InteractiveBrowserCredential` from `@azure/identity`).
  [PR 11250](https://github.com/Azure/azure-sdk-for-js/pull/11250)
```

2020-10-08 01:44 UTC, joheredi commented on releases/2020-10/js.md
> +- Implemented batch operations.
```suggestion
- Implemented support for batch operations. This allows sending multiple create, delete and update operations in a single atomic transaction.
```

2020-10-12 04:23 UTC, joheredi commented on releases/2020-10/js.md
> +- Implemented batch operations.
updated the description

2020-10-12 22:15 UTC, sarangan12 commented on releases/2020-10/js.md
> +TODO
- Added Batching ability to the search SDK. Please refer [#11544](https://github.com/Azure/azure-sdk-for-js/pull/11544) for further details.
- Regenerated the search SDK using the latest swaggers. Please refer [#11533](https://github.com/Azure/azure-sdk-for-js/pull/11533) for further details.
- Fixed the testcases to ensure success in CI. Please refer [#11518](https://github.com/Azure/azure-sdk-for-js/pull/11518) for further details.
- Added more test cases for odata scenario. Please refer [#11321](https://github.com/Azure/azure-sdk-for-js/pull/11321) for further details.

2020-10-13 11:23 UTC, ljian3377 requested changes

2020-10-13 11:23 UTC, ljian3377 commented on releases/2020-10/js.md
> +### Azure Storage File Share.
```suggestion
### Azure Storage

Updated Azure Storage Service API version to 2020-02-10.

#### @azure/storage-blob [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-blob/CHANGELOG.md)

##### New Features on @azure/storage-blob@12.3.0-beta.1

- Added support for Container Soft Delete. Added a new API `BlobServiceClient.undeleteContainer()` to restore a previously deleted blob container.

#### @azure/storage-file-datalake [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-file-datalake/CHANGELOG.md)

##### New Features on @azure/storage-file-datalake@12.2.0-beta.1

- Added support for directory SAS and delegation SAS v2. Now supports generate SAS on directory level. Also added support for `saoid`, `suoid` and `scid` for delegation SAS. See the user delegation SAS [document](https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#specify-a-signed-object-id-for-a-security-principal-preview) for more details.
- Added support for File Set Expiry. Now can call `DataLakeFileClient.setExpiry()` to schedule the deletion of a file.
- Added `DataLakePathClient.setAccessControlRecursive()` to support setting access control recursively. 

#### storage-file-share [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-file-share/CHANGELOG.md)

##### New Features on @azure/storage-file-share@12.3.0-beta.1

- Added support for Share and Share Snapshot Leases. Now can initialize a `ShareLeaseClient` with a `ShareClient` to manage leases for a share or share snapshot. Most operations on share now also support lease conditions.
- Added support for Get File Range Diff. Added `ShareFileClient.getRangeListDiff()` for getting the list of ranges that differ between a previous share snapshot and the file.
- Added support for Set Share Tier. Added `ShareClient.setAccessTier()` for setting the access tier of the share.
```

2020-10-13 11:23 UTC, ljian3377 commented on releases/2020-10/js.md
> +TODO
```suggestion
```

2020-10-13 11:23 UTC, ljian3377 commented on releases/2020-10/js.md
> +### Azure Storage Data Lake.
```suggestion
```

2020-10-13 11:23 UTC, ljian3377 commented on releases/2020-10/js.md
> +TODO
```suggestion
```

2020-10-13 11:23 UTC, ljian3377 commented on releases/2020-10/js.md
> +### Azure Storage Blob.
```suggestion
```

2020-10-13 11:23 UTC, ljian3377 commented on releases/2020-10/js.md
> +TODO
```suggestion
```

2020-10-13 17:14 UTC, sadasant commented
@ljian3377 thank you!

2020-10-13 17:26 UTC, sadasant commented on releases/2020-10/js.md
> +TODO
Updated!

2020-10-13 18:04 UTC, ramya-rao-a commented on releases/2020-10/js.md
> +- Added support for multiple clouds on `VisualStudioCodeCredential`. Fixes customer issue [11452](https://github.com/Azure/azure-sdk-for-js/issues/11452).
We do not usually link to individual issues from the high level release notes. That level of detail makes more sense in the changelog

```suggestion
- Added support for multiple clouds on `VisualStudioCodeCredential`. 
```

2020-10-13 18:04 UTC, ramya-rao-a commented on releases/2020-10/js.md
> +- `ManagedIdentityCredential` has been aligned with other languages, now treating expected errors properly. This fixes customer issue [11451](https://github.com/Azure/azure-sdk-for-js/issues/11451)
Does this result in the user changing their code in any way? If it does not, then this would not be considered as a "developer impacting change" and I would remove this from the highlights

2020-10-13 18:04 UTC, ramya-rao-a commented on releases/2020-10/js.md
> +### Azure Storage
Since this is not yet released... 

```suggestion
### Azure Storage (Coming Soon)
```

2020-10-13 18:06 UTC, sadasant commented on releases/2020-10/js.md
> +- `ManagedIdentityCredential` has been aligned with other languages, now treating expected errors properly. This fixes customer issue [11451](https://github.com/Azure/azure-sdk-for-js/issues/11451)
It's a bug fix 🤔

2020-10-13 18:39 UTC, sadasant commented on releases/2020-10/js.md
> +- `ManagedIdentityCredential` has been aligned with other languages, now treating expected errors properly. This fixes customer issue [11451](https://github.com/Azure/azure-sdk-for-js/issues/11451)
Removed!

2020-10-13 19:03 UTC, ramya-rao-a commented
@weshaggard The "Verify site links" step has been running for over 17 minutes now. Is that normal for that step?

cc @jongio, @czubair  

<img width="344" alt="image" src="https://user-images.githubusercontent.com/16890566/95904250-18d1a480-0d4c-11eb-9db2-3aa85656f542.png">

2020-10-13 19:30 UTC, ramya-rao-a approved these changes

2020-10-13 19:30 UTC, merged