Template for Migration guide
Azure/azure-sdk pull request #2132
Opened 2020-12-08 01:33 UTC by ramya-rao-a

This PR adds a template for the migration guide to be used when Track 2 packages replace an existing Track 1 package.

2020-12-08 01:35 UTC, ramya-rao-a commented on docs/policies/migration-guide-template.md
> +- (In case of JS) use of async iterators in paging APIs
We should add language specific common cross service improvements here

@JonathanGiles, @annatisch, @tg-msft, @bterlson Anything to add for your languages?

2020-12-08 17:22 UTC, weshaggard commented on docs/policies/migration-guide-template.md
> +# Guide for migrating to [name of Track 2 package here] from [name of Track 1 package here]
Should we use new and old package here instead of track 1 and track 2 terms?

2020-12-08 22:23 UTC, ramya-rao-a commented on docs/policies/migration-guide-template.md
> +# Guide for migrating to [name of Track 2 package here] from [name of Track 1 package here]
Sounds good. I have made sure we don't use these terms in the actual content and are present only in the placeholders, but I can make the change as well

2020-12-10 18:42 UTC, conniey commented on docs/policies/migration-guide-template.md
> +
nit: trailing empty lines.

2020-12-10 22:51 UTC, mccoyp reviewed
nit: some things I noticed while writing the migration guide for Key Vault

2020-12-10 22:51 UTC, mccoyp commented on docs/policies/migration-guide-template.md
> +Familiarity with the [name of Track 1 package here] package is assumed. For those new to the [service name here] client library for [language here .Net/JavaScript/Python/Java], please refer to the [R
```suggestion
Familiarity with the [name of Track 1 package here] package is assumed. For those new to the [service name here] client library for [language here .Net/JavaScript/Python/Java], please refer to the [README for name of Track 2 package here](add link to track 2 readme) rather than this guide.
```

2020-12-10 22:51 UTC, mccoyp commented on docs/policies/migration-guide-template.md
> +A natural question to ask when considering whether or not to adopt a new version or library is what the benefits of doing so would be. As Azure has matured and been embraced by a more diverse group o
```suggestion
A natural question to ask when considering whether or not to adopt a new version or library is what the benefits of doing so would be. As Azure has matured and been embraced by a more diverse group of developers, we have been focused on learning the patterns and practices to best support developer productivity and to understand the gaps that the [language here .NET/JavaScript/Python/Java] client libraries have.
```

2020-12-15 20:08 UTC, ramya-rao-a commented on docs/policies/migration-guide-template.md
> +
Fixed in https://github.com/Azure/azure-sdk/pull/2132/commits/216ace0b3db283842f1cb20206f2ed0d1d26991c

2020-12-15 20:08 UTC, ramya-rao-a commented on docs/policies/migration-guide-template.md
> +Familiarity with the [name of Track 1 package here] package is assumed. For those new to the [service name here] client library for [language here .Net/JavaScript/Python/Java], please refer to the [R
Fixed in https://github.com/Azure/azure-sdk/pull/2132/commits/216ace0b3db283842f1cb20206f2ed0d1d26991c

2020-12-15 20:08 UTC, ramya-rao-a commented on docs/policies/migration-guide-template.md
> +A natural question to ask when considering whether or not to adopt a new version or library is what the benefits of doing so would be. As Azure has matured and been embraced by a more diverse group o
Fixed in https://github.com/Azure/azure-sdk/pull/2132/commits/216ace0b3db283842f1cb20206f2ed0d1d26991c

2020-12-15 20:09 UTC, ramya-rao-a commented on docs/policies/migration-guide-template.md
> +# Guide for migrating to [name of Track 2 package here] from [name of Track 1 package here]
Fixed in https://github.com/Azure/azure-sdk/pull/2132/commits/f4dd2025c87f6f4ce615ae4687d2ba527381137e

2020-12-21 19:12 UTC, yunhaoling commented on docs/policies/migration-guide-template.md
> +## Table of contents
what should be put into this section?

2020-12-21 19:33 UTC, ramya-rao-a commented on docs/policies/migration-guide-template.md
> +## Table of contents
Links to the different headers/sections in the page.

2021-01-15 21:28 UTC, bterlson approved these changes

2021-01-15 21:28 UTC, bterlson commented on docs/policies/migration-guide-template.md
> +A natural question to ask when considering whether or not to adopt a new version or library is what the benefits of doing so would be. As Azure has matured and been embraced by a more diverse group o
I appreciate validating the reasons I'm reading this readme in the first place, but it's maybe not necessary 😁

```suggestion
As Azure has matured and been embraced by a more diverse group of developers, we have been focused on learning the patterns and practices to best support developer productivity and to understand the gaps that the [language here .NET/JavaScript/Python/Java] client libraries have.
```

2021-01-15 21:28 UTC, bterlson commented on docs/policies/migration-guide-template.md
> +To try and improve the development experience across Azure services, a set of uniform [design guidelines](https://azure.github.io/azure-sdk/general_introduction.html) was created for all languages to
```suggestion
To improve the development experience across Azure services, a set of uniform [design guidelines](https://azure.github.io/azure-sdk/general_introduction.html) was created for all languages to drive a consistent experience with established API patterns for all services. A set of [add language here-specific guidelines](add link to language specific guidelines here) was also introduced to ensure that [add language here] clients have a natural and idiomatic feel with respect to the [add language here] ecosystem. The new [name of new package nere] follows these guidelines.
```

2021-01-15 21:28 UTC, bterlson commented on docs/policies/migration-guide-template.md
> +To try and improve the development experience across Azure services, a set of uniform [design guidelines](https://azure.github.io/azure-sdk/general_introduction.html) was created for all languages to
Don't be modest 😎

2021-01-16 00:45 UTC, KrzysztofCwalina approved these changes
In addition to these two comments, I think it would be great to point this template at examples of well written guides.

2021-01-16 00:45 UTC, KrzysztofCwalina commented on docs/policies/migration-guide-template.md
> +Use this section to advertise the performance improvements in new package when compared to the old one. Skip this section if no perf improvements are found yet.
For .NET, the improvements should be illustrated with Benchmark.NET benchmark results.

2021-01-16 00:45 UTC, KrzysztofCwalina commented on docs/policies/migration-guide-template.md
> +More examples can be found at [Samples for add package name here](Add link to samples here)
It might be worth adding a section with important gotchas.

2021-01-20 17:53 UTC, salameer commented
Hi Ramya, 

How will this fit in with the Migration Guide requirements here:

https://azure.github.io/azure-sdk/policies_releases.html#2-change-logs--migration-guides

Or the content there be replaced with a link here?

2021-01-20 18:09 UTC, salameer commented
One more comment, I think this should be part of the exit criteria rather than a separate policy

2021-01-21 16:53 UTC, salameer requested changes
Hi Ramya, Please see my comments at the bottom. I would recommend referencing migration guides from the Exit criteria page and not having this as a separate policy.

2021-01-29 06:51 UTC, ramya-rao-a commented
@sameralameer,

> How will this fit in with the Migration Guide requirements here:
https://azure.github.io/azure-sdk/policies_releases.html#2-change-logs--migration-guides
Or the content there be replaced with a link here?

The content there will not be replaced. We will only add a link to the migration guide template from there i.e. the `Changelogs & Migration Guides` section in the exit criteria. 

> One more comment, I think this should be part of the exit criteria rather than a separate policy

Do you mean that this file should live elsewhere? Can you point me to the desired location?

2021-01-29 07:00 UTC, ramya-rao-a commented on docs/policies/migration-guide-template.md
> +Use this section to advertise the performance improvements in new package when compared to the old one. Skip this section if no perf improvements are found yet.
In the perf discussions recently, there were still debates on whether Benchmark.NET should be used at all. Will leave this to the .Net team to decide and update the migration guide independent of this PR

2021-01-29 18:15 UTC, salameer approved these changes

2021-01-29 18:21 UTC, ramya-rao-a commented
> Do you mean that this file should live elsewhere? Can you point me to the desired location?

Samer and I synced offline. We are going ahead with this PR and then Samer will do the needful to ensure that this does not show up as a "policy"

2021-01-29 21:25 UTC, ramya-rao-a commented
@weshaggard The build fails with a broken link error

> ##[warning][404] broken link ***-for-python/tree/azure-search_1.0.0b2/sdk/search/azure-search/

Can you help with this?

2021-01-29 23:10 UTC, merged