Unify lang releases md
Azure/azure-sdk pull request #2216
Opened 2021-01-07 22:33 UTC by vhvb1989

fixes: #2215 

- Unify the latest releases for all languages in one only md file and use it instead.
- Replace home root page for a meta redirect page.

2021-01-07 23:31 UTC, ahsonkhan commented
What happens now if someone goes to the releases link explicitly?

Both these links seem to hit a 404. Why is that?
https://vhvb1989.github.io/azure-sdk/releases
https://vhvb1989.github.io/azure-sdk/releases/latest/ (note the extra `/` at the end of the URL)

![image](https://user-images.githubusercontent.com/6527137/103956324-2903e080-50fd-11eb-8a08-0bda68d62ace.png)

2021-01-07 23:36 UTC, ahsonkhan commented on index.html
> +      `./releases/latest`
Are we sure we want this sort of redirection? I am not familiar with our docs web dev, so don't know of an alternative solution. Maybe someone else can help shed some light on best practices around link navigation here.

2021-01-07 23:36 UTC, ahsonkhan commented on _includes/releases/eachLanguage.md
> ----
Looks like all markdown files have this title/layout metadata. Is it OK to remove it?

2021-01-08 01:50 UTC, vhvb1989 commented on index.html
> +      `./releases/latest`
I would let @weshaggard  and/or @jongio  decide.

What I am trying to resolve is that we have 2 pages that are expected to look exactly the same:
- root page: display the latest release page
- /releases/latest: also display the same info

There is no difference expected between the two of them.  However, like we can see in the actual issue, the can go out of sync easily and display fewer data from one of them.

The other issue is related to the sidebar which reacts to the navigation path to highlight an item from the list.
The js script comes from an 3rd party, so we don't have full control over it to easily override its behavior. This makes super hard to have the highlighting and same behavior we have on `releases/latest` on the root `/`

That's the reason I am recommending and suggesting to just redirect root page to `releases/latest` to make it the root page at any case.

2021-01-08 01:51 UTC, vhvb1989 commented on _includes/releases/eachLanguage.md
> ----
This metadata is used by Jekyll to auto-generate the html page based on some pre-defined templates/layout

I am basically removing this from the root page and instead just leaving a raw html file to make the redirection. :)

2021-01-08 02:00 UTC, vhvb1989 commented
> What happens now if someone goes to the releases link explicitly?

Same bahavior as before.  And usually that's the workaround people could have been applying. Instead of going the the site root, always using the releases/latest link instead (as it looks better)

> https://vhvb1989.github.io/azure-sdk/releases

That's expected. The browser is trying to find some index file inside the releases folder (which we don't have)

> https://vhvb1989.github.io/azure-sdk/releases/latest/ (note the extra `/` at the end of the URL)

Also expected. We are asking to find an index file inside a folder with an empty name ("") within the latest folder.  Some servers are a little more intelligent and will understand the empty name as a way to go up one level to the previous folder. That would make the request to work. But that's now our case :).

Btw. We could also leave the `/index.html` as part of the path as before. But IMHO it doesn't look good. We can have shorter and still functional links by letting the server look for the default html file within the folder

2021-01-08 02:09 UTC, weshaggard commented on index.html
> +      `./releases/latest`
I don't think we should do a redirect like this there are definitely some drawbacks, one of them is that web crawlers generally don't like them (see https://www.weboptimizers.com.au/google-warning-meta-refresh/). 

Instead of redirecting perhaps we can just refactor these includes into another md file and then include that in both places. It will be duplicated content but it will ensure we share.

2021-01-08 18:50 UTC, vhvb1989 commented on index.html
> +      `./releases/latest`
@weshaggard  yeah, they don't have the best reputation because they are mostly used by adds pages 🗡️ 

I read the link you shared, and I think we are not doing anything of what they said is wrong. Anyway, I understand we would want to avoid it better.

> perhaps we can just refactor these includes into another md file and then include that in both 

That is also what I did on this PR.  Redirecting to remove one page was a bonus :) .  I will update this PR to only let the first change and undo the `redirect`. I can open another issue to see how we can resolve the sidebar highlighting issue without the redirect strategy.

2021-01-08 19:06 UTC, jongio commented
No redirect please.  Thanks

2021-01-08 19:25 UTC, vhvb1989 commented
> 
> 
> No redirect please. Thanks

@jongio  yes, I have updated the PR to remove that. Only leaving the unify change to sync both pages.  :)

2021-01-08 19:51 UTC, jongio requested changes

2021-01-08 19:51 UTC, jongio commented on _includes/releases/eachLanguage.md
> +{% include releases/dotnet.md type="client" %}
rename to all.md or alllangs.md

2021-01-08 20:46 UTC, RickWinter commented on _includes/releases/eachLanguage.md
> +{% include releases/dotnet.md type="client" %}
languages.md gets my vote. :)

2021-01-08 21:02 UTC, vhvb1989 commented on _includes/releases/eachLanguage.md
> +{% include releases/dotnet.md type="client" %}
updated to `languages.md`

2021-01-08 23:29 UTC, jongio approved these changes

2021-01-08 23:50 UTC, weshaggard approved these changes
Thanks.

2021-01-08 23:51 UTC, weshaggard commented on index.html
> +      `./releases/latest`
Thanks for fixing and filing issues. Hopefully we can figure out how to fix the highlighting.

2021-01-08 23:51 UTC, merged