Update names and add more service names
Azure/azure-sdk pull request #2225
Opened 2021-01-11 12:49 UTC by v-xuto

Update names and add more service names in donet, python, js and java csv files.

@jongio for notification.

2021-01-11 17:24 UTC, weshaggard commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.CognitiveServices.Speech","1.14.0","","Text to Speech","Text to Speech","NA","NA","NA","","client","false",""
Why were these manually added? In general if there are packages not in this list but are published to nuget we need to get azure-sdk added as an owner for those packages and they will automatically get added. 

Also for these entries it looks like are missing at least one field as you have the field "New" set to "client" which isn't correct.

2021-01-12 01:10 UTC, jongio commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.CognitiveServices.Speech","1.14.0","","Text to Speech","Text to Speech","NA","NA","NA","","client","false",""
@weshaggard - It looks like azure-sdk is owner of this package.  Can you see why the script didn't pick it up?

2021-01-12 01:13 UTC, jongio requested changes

2021-01-12 01:13 UTC, jongio commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.CognitiveServices.Speech","1.14.0","","Text to Speech","Text to Speech","NA","NA","NA","","client","false",""
Microsoft.CognitiveServices.Speech

2021-01-12 01:13 UTC, jongio commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.Azure.RemoteRendering","0.1.61","","","Remote Rendering","NA","NA","NA","","client","false",""
@weshaggard azure-sdk not owner here: https://www.nuget.org/packages/Microsoft.Azure.RemoteRendering.Cpp/

2021-01-12 01:13 UTC, jongio commented on _data/releases/latest/js-packages.csv
> +"@microsoft/immersive-reader-sdk","0.5.2","","Immersive Reader","Immersive Reader","https://github.com/microsoft/immersive-reader-sdk","NA","NA","client","false","",""
@weshaggard - This is not a package, just scripts in github, but still a T1 sdk that we provide

2021-01-12 01:20 UTC, weshaggard commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.CognitiveServices.Speech","1.14.0","","Text to Speech","Text to Speech","NA","NA","NA","","client","false",""
This one is already in the file. See line 532.

2021-01-12 01:22 UTC, weshaggard commented on _data/releases/latest/js-packages.csv
> +"@microsoft/immersive-reader-sdk","0.5.2","","Immersive Reader","Immersive Reader","https://github.com/microsoft/immersive-reader-sdk","NA","NA","client","false","",""
That seems a little odd. It isn't even in the azure namespace and not on npm but if we need it for tracking purposes I can live with it being added.

2021-01-13 00:14 UTC, jongio commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.Azure.Devices.Client","1.33.1","","Devices Client","IoT Plug and Play","NA","NA","NA","client","False","",""
Are you sure this is for Plug and Play?

2021-01-13 00:14 UTC, jongio commented on _data/releases/latest/java-packages.csv
> +"iot-device-client","com.microsoft.azure","1.1.24","","IoT Plug and Play","IoT","NA","NA","NA","client","false","true",""
Why Plug and Play.  I doubt these are PnP

2021-01-13 01:35 UTC, v-xuto commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.Azure.Devices.Client","1.33.1","","Devices Client","IoT Plug and Play","NA","NA","NA","client","False","",""
@jongio - I refer to this link: https://docs.microsoft.com/en-us/azure/iot-pnp/libraries-sdks

2021-01-13 01:35 UTC, v-xuto commented on _data/releases/latest/java-packages.csv
> +"iot-device-client","com.microsoft.azure","1.1.24","","IoT Plug and Play","IoT","NA","NA","NA","client","false","true",""
Same as above

2021-01-13 18:37 UTC, weshaggard commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.Azure.RemoteRendering","0.1.61","","Remote Rendering","Remote Rendering","NA","NA","NA","","client","false",""
```suggestion
"Microsoft.Azure.RemoteRendering","0.1.61","","Remote Rendering","Remote Rendering","NA","NA","NA","client","false","",""
```
I think a number of these have the fields shifted by 1 and so you should shift them over.

2021-01-19 17:02 UTC, weshaggard commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.CognitiveServices.Speech","1.14.0","","Speech to Text","Speech to Text","NA","NA","NA","client","False","",""
Why is this in here twice?

2021-01-19 17:07 UTC, weshaggard commented on _data/releases/latest/js-packages.csv
> +"microsoft-cognitiveservices-speech-sdk","1.14.1","","Speech to Text","Speech to Text","NA","https://docs.microsoft.com/javascript/api/overview/azure/speech-service","NA","client","false","",""
Why is this listed twice?

2021-01-19 17:07 UTC, weshaggard commented on _data/releases/latest/python-packages.csv
> +"azure-cognitiveservices-speech","1.14.0","","Text to Speech","Text to Speech","NA","NA","NA","client","false","",""
Why is this listed twice?

2021-01-19 17:10 UTC, weshaggard approved these changes
Aside from the duplicate speech SDK libraries the changes look good.

2021-01-19 17:16 UTC, jongio approved these changes

2021-01-19 17:16 UTC, jongio commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.CognitiveServices.Speech","1.14.0","","Text to Speech","Text to Speech","NA","NA","NA","client","False","",""
Please don't include sub-services like this in the CSVs.  Thanks. Only include the primary service.  The sub-services are needed for inventory, but we can manually add those.

2021-01-19 19:48 UTC, merged