February release highlights for JavaScript & TypeScript
Azure/azure-sdk pull request #2333
Opened 2021-02-04 19:54 UTC by sadasant

February release notes for JavaScript and TypeScript.

Please suggest changes with your release notes.

If you're looking for inspiration:

- [What's a Developer Impacting Change?](https://github.com/Azure/azure-sdk/blob/08f279b39a4c19822b1509e6b10fc3ce256607b5/docs/policies/releasenotes.md#whats-a-developer-impacting-change).
- Highlight guidelines: <https://azure.github.io/azure-sdk/policies_releasenotes.html>
- September's PR: #1750
- October's PR: #1878
- November's PR: #2029
- December's PR: #2138
- January's PR: #2240

2021-02-04 19:58 UTC, sadasant commented on releases/2021-02/index.md
> +* Azure Search Documents is releasing a new GA.
Please propose what highlights should be mentioned independently of the language.

2021-02-09 17:11 UTC, witemple-msft commented
@sadasant The phrasing of "changes on" sounds strange to me, and I think we should replace it with "in" in the section headers. ("changes on @azure/xyz@1.2.3" -> "changes in @azure/xyz@1.2.3"). I'll fill out my notes according to the template here, but this is just some extra feedback.

2021-02-09 17:19 UTC, witemple-msft commented on releases/2021-02/js.md
> +- Azure AI Form Recognizer
```suggestion
- Azure Text Analytics
- Azure Metrics Advisor
- Azure Form Recognizer
```

IIRC, we use `ai-form-recognizer` as the package name, but the product name is just "Form Recognizer". Same for the others. (CC @deyaaeldeen @jeremymeng)

2021-02-09 17:19 UTC, witemple-msft commented on releases/2021-02/js.md
```suggestion

### Azure Form Recognizer

#### @azure/ai-form-recognizer [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/formrecognizer/ai-form-recognizer/CHANGELOG.md)

##### Breaking Changes on @azure/ai-form-recognizer@3.1.0-beta.2

- Reworked the type of the `appearance` field and its children of the `FormLine` type to have more specific names.

```

@sadasant This is only a breaking change with respect to the previous beta `3.1.0-beta.1`. Should it still be filed as a breaking change here?

2021-02-09 21:14 UTC, chradek reviewed
Leaving comments for the Event Hubs package.

2021-02-09 21:14 UTC, chradek commented on releases/2021-02/js.md
> +$> npm install @azure/event-hubs@next
Event Hubs is a GA release, so we shouldn't need the `@next` tag.

2021-02-09 21:14 UTC, chradek commented on releases/2021-02/js.md
> +- Azure File Share
```suggestion
- Azure File Share
- Azure Event Hubs
```

2021-02-09 21:14 UTC, chradek commented on releases/2021-02/js.md
> +- Azure Event Hubs
Event Hubs is a GA release, not beta.
```suggestion
```

2021-02-09 21:14 UTC, chradek commented on releases/2021-02/js.md
> +
```suggestion
### Event Hubs

#### @azure/event-hubs [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventhub/event-hubs/CHANGELOG.md)

##### New Features on @azure/event-hubs@5.4.0

- You can now specify specify custom endpoint address as a client constructor option to use when communicating with the Event Hubs service, which is useful when your network does not allow communicating to the standard Event Hubs endpoint.

- Added a helper method `parseEventHubConnectionString` that can be used to validate and parse a given connection string for Azure Event Hubs.

##### Major Fixes on @azure/event-hubs@5.4.0

- Fixes an issue where the `RetryMode` enum for use when setting the RetryOptions.mode field in EventHubConsumerClientOptions or EventHubClientOptions wasn't exported by the package.

```

2021-02-10 06:17 UTC, ljian3377 commented on releases/2021-02/js.md
> +- Azure Storage Blob
```suggestion
- Azure Storage Blob
- Azure File Datalake
```

2021-02-10 06:19 UTC, ljian3377 commented on releases/2021-02/js.md
> +$> npm install @azure/storage-blob@next
```suggestion
$> npm install @azure/storage-blob@next
$> npm install @azure/storage-file-datalake@next
```

2021-02-10 06:47 UTC, ljian3377 commented on releases/2021-02/js.md
```suggestion

### Azure Storage

We released hot fix versions and also beta versions for new service features in Azure Storage Service API version 2020-06-10.

#### @azure/storage-blob [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-blob/CHANGELOG.md)

##### New Features on @azure/storage-blob@12.5.0-beta.1

- Now support Batch operations scoped to the Container level. You can use `ContainerClient.getBlobBatchClient()` to get such a `BlobBatchClient`.

##### Major Fixes on @azure/storage-blob@12.4.1

- Fixed a compile failure due to "Can't resolve 'crypto'" in Angular. [Issue #13267](https://github.com/Azure/azure-sdk-for-js/issues/13267).
- Fixed an issue that the download stream returned by `BlobClient.download` won't release underlying resources unless it's fully consumed. [Isssue #11850](https://github.com/Azure/azure-sdk-for-js/issues/11850).

#### @azure/storage-file-datalake [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-file-datalake/CHANGELOG.md)

##### New Features on @azure/storage-file-datalake@12.4.0-beta.1

- Added support for Container Soft Delete. You can restore a deleted filesystem via `DataLakeServiceClient.undeleteFileSystem()`. And the `DataLakeServiceClient.listFileSystems()` now support an `includeDeleted` option to include soft deleted filesystems in the response.

##### Major Fixes on @azure/storage-file-datalake@12.3.1

- Fixed a compile failure due to "Can't resolve 'crypto'" in Angular. [Issue #13267](https://github.com/Azure/azure-sdk-for-js/issues/13267).

#### storage-file-share [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-file-share/CHANGELOG.md)

##### @azure/storage-file-share@12.4.1

This release contains bug fixes to improve quality.

#### storage-queue [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-queue/CHANGELOG.md)

##### @azure/storage-queue@12.3.1

This release contains bug fixes to improve quality.

```

2021-02-10 18:29 UTC, sadasant commented on releases/2021-02/js.md
> +- Azure AI Form Recognizer
Thank you!

2021-02-10 18:33 UTC, sadasant commented on releases/2021-02/js.md
@witemple-msft up to you! How would it be better for our customers? I can think of arguments on favor and against using breaking change here. It feels like since this is a beta it would be better to state it as an update... but I'm not strongly on favor of it!

2021-02-10 18:37 UTC, sadasant commented on releases/2021-02/js.md
On the other hand, these titles are a bit arbitrary! So I don't mind changing one of them. I'll set that header as "Changes" instead of "Breaking changes". Let me know if that sounds ok or not 🌞

2021-02-10 18:38 UTC, sadasant commented on releases/2021-02/js.md
> +- Azure File Share
I moved event hubs to the GA section 🌞 thanks for the update!

2021-02-10 18:53 UTC, sadasant commented on releases/2021-02/js.md
> +- Azure AI Form Recognizer
I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55

2021-02-10 18:53 UTC, sadasant commented on releases/2021-02/js.md
I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55

2021-02-10 18:53 UTC, sadasant commented on releases/2021-02/js.md
> +- Azure File Share
I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55

2021-02-10 18:54 UTC, sadasant commented on releases/2021-02/js.md
> +
Thank you! I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55

2021-02-10 18:54 UTC, sadasant commented on releases/2021-02/js.md
> +$> npm install @azure/storage-blob@next
Thank you! I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55

2021-02-10 18:54 UTC, sadasant commented on releases/2021-02/js.md
Thank you! I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55

2021-02-10 18:55 UTC, sadasant commented
@witemple-msft @chradek @ljian3377 Thank you! I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55 Please review again!

2021-02-10 18:56 UTC, sadasant commented on releases/2021-02/js.md
> +- Azure Storage Blob
Thank you! I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55

2021-02-10 18:57 UTC, sadasant commented on releases/2021-02/js.md
> +- Azure Event Hubs
Thank you! I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55

2021-02-10 18:57 UTC, sadasant commented on releases/2021-02/js.md
> +$> npm install @azure/event-hubs@next
Thank you! I have pushed an update here: https://github.com/Azure/azure-sdk/pull/2333/commits/ce3ac4b7e18b5327628227ac86cd9b97405f2b55

2021-02-10 19:15 UTC, deyaaeldeen commented on releases/2021-02/js.md
>  ## Latest Releases
```suggestion
### Azure Text Analytics

#### @azure/ai-text-analytics [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/textanalytics/ai-text-analytics/CHANGELOG.md)

##### New Features in @azure/ai-text-analytics@5.1.0-beta.4

- A new option to control how the offset is calculated by the service, `stringIndexType`, is added to `analyzeSentiment`, `recognizeEntities`, `recognizePiiEntities`, and `beginAnalyzeHealthcareEntities`. Furthermore, `stringIndexType` is added to task types `RecognizeEntitiesAction` and `RecognizePiiEntitiesAction`, which are the types of input actions to the `beginAnalyzeBatchActions` method. For more information, see [the Text Analytics documentation](https://docs.microsoft.com/azure/cognitive-services/text-analytics/concepts/text-offsets#offsets-in-api-version-31-preview).
- The poller for the `beginAnalyzeBatchActions` long-running operation gained the ability to return certain metadata information about the currently running operation (e.g., when the operation was created, will be expired, and last time it was updated, and also how many actions completed and failed so far). Also, the poller for `beginAnalyzeHealthcareEntities` gained a similar ability.

##### Breaking Changes on @azure/ai-text-analytics@5.1.0-beta.4

- `beginAnalyzeHealthcare` is renamed to `beginAnalyzeHealthcareEntities`.
- `beginAnalyze` is renamed to `beginAnalyzeBatchActions`.
- The healthcare entities returned by `beginAnalyzeHealthcare` are now organized as a directed graph where the edges represent a certain type of healthcare relationship between the source and target entities. Edges are stored in the `relatedEntities` property.
- The `links` property of `HealthcareEntity` is renamed to `dataSources`, a list of objects representing medical databases, where each object has `name` and `entityId` properties.
- the words "operation" and "action" are used consistently in our names and documentation instead of "job" and "task" respectively.

## Latest Releases
```

2021-02-10 20:11 UTC, maorleger commented on releases/2021-02/js.md
> +
```suggestion

### Azure Key Vault Admin [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-admin/CHANGELOG.md)

- We've added support for RBAC in Managed HSM instances. Users can now use the administration client to create custom role definitions and create role assignments.

### Azure Key Vault Keys [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/keyvault/keyvault-keys/CHANGELOG.md)

- Added a constructor overload to CryptographyClient that takes a JsonWebKey and allows for local-only subset of operations.
- Added a createOctKey convenience method to create a key of type oct or oct-HSM as appropriate.

```

Something like this? It's my first time! 😄

2021-02-10 22:06 UTC, ellismg commented on releases/2021-02/js.md
> +This release contains bug fixes to improve quality.
```suggestion
This release contains bug fixes to improve quality.

### Azure Event Grid

We released a new beta package for the Event Grid service.

#### @azure/eventgrid [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventgrid/eventgrid/CHANGELOG.md)

##### Breaking changes in @azure/eventgrid@3.0.0-beta.3

- The type definitions for SMS events sent by Azure Communication Services have been renamed, to use the prefix "AcsSms" instead of "Acssms". If you are using TypeScript and explicitly referencing these interfaces, you will need to update your code to use the new names. The payload of the events is unchanged.
- `EventGridSharedAccessCredential` has been removed, in favor of `AzureSASCredential`. Code which is using `EventGridSharedAccessCredential` should now use `AzureSASCredential` instead.
- When constructing the client, you must now include the schema type your topic is configured to expect (one of "EventGrid", "CloudEvent" or "Custom").
- The `sendEvents` methods have been collapsed into a single method on the client called `send` which uses the input schema that was configured on the client.

##### New Features in @azure/eventgrid@3.0.0-beta.3

- Added distributed tracing support. EventGridProducerClient will now create spans when sending events to Event Grid.
```

2021-02-10 23:14 UTC, sadasant commented on releases/2021-02/js.md
>  ## Latest Releases
Can we make this shorter? It should not be exactly like the changelog entry. 🙏

2021-02-10 23:22 UTC, sadasant commented on releases/2021-02/js.md
> +
More like this https://github.com/Azure/azure-sdk/pull/2333/commits/ba6893286c3b904ce4870db1c3012e559a835ce7#diff-a1ff6f8d1225133bd78843c3c728c052d26119ab995b81106191195e06d295a4R78-R94

Are we not releasing certificates and secrets? 🤔

2021-02-10 23:37 UTC, sadasant commented on releases/2021-02/js.md
> +This release contains bug fixes to improve quality.
Thanks! I'll add it in a bit 🌞

2021-02-10 23:54 UTC, maorleger commented on releases/2021-02/js.md
> +
Done!

2021-02-11 00:18 UTC, sadasant commented on releases/2021-02/js.md
> +
nice!!! thanks!

2021-02-11 00:28 UTC, sadasant commented on releases/2021-02/js.md
> +This release contains bug fixes to improve quality.
Added it! Please review again 🙏

2021-02-11 00:56 UTC, weshaggard commented on releases/2021-02/js.md
> +- Azure Storage Blob
Should these be package names?

2021-02-11 00:56 UTC, weshaggard commented on releases/2021-02/js.md
> +#### @azure/event-hubs [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventhub/event-hubs/CHANGELOG.md)
It is best to have change log entries use the release tags instead of master.

2021-02-11 02:32 UTC, sadasant commented on releases/2021-02/js.md
> +- Azure Storage Blob
We've been using the product name each time we do these highlights 🤔 we could change it!

2021-02-11 18:11 UTC, weshaggard commented on releases/2021-02/js.md
> +- Azure Storage Blob
I don't have any strong preference here but we should see if this list adds enough value over the other parts below.

2021-02-11 18:24 UTC, sadasant commented on releases/2021-02/js.md
>  ## Latest Releases
Woah! thanks!

2021-02-11 18:27 UTC, sadasant commented on releases/2021-02/js.md
>  ## Latest Releases
I have added it! Thank you!

2021-02-11 18:28 UTC, sadasant commented on releases/2021-02/js.md
> +#### @azure/event-hubs [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventhub/event-hubs/CHANGELOG.md)
Done! Except for one identity entry that is going out today

2021-02-11 19:06 UTC, KarishmaGhiya commented on releases/2021-02/js.md
```suggestion
### AI Metrics Advisor

- We are releasing a new  preview version for metrics advisor with AAD support feature

#### @azure/ai-metrics-advisor [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/metricsadvisor/ai-metrics-advisor/CHANGELOG.md)

###  New Features in @azure/ai-metrics-advisor@1.0.0@beta.3

- Metrics Advisor is releasing support for Azure Active Directory Authentication and support to rotate the API and Subscription Keys.

```

2021-02-11 19:30 UTC, sadasant commented on releases/2021-02/js.md
Added! Thank you!

2021-02-11 19:42 UTC, Mohit-Chakraborty commented on releases/2021-02/index.md
> +* Azure Search Documents is releasing a new GA.
This is one candidate -

- Adds support for indexing search documents with intelligent batching, automatic flushing, and retries for failed indexing actions.

cc: @tg-msft, @alzimmermsft

2021-02-11 19:47 UTC, jeremymeng commented on releases/2021-02/js.md
> +### AI Metrics Advisor
```suggestion
### Metrics Advisor
```
Do we need to have `Azure` in the front? Looks like Event Hubs heading doesn't have it.

2021-02-11 20:07 UTC, sadasant commented on releases/2021-02/js.md
> +### AI Metrics Advisor
Azure products generally have Azure in front, so I will add it! Thank you for noticing this.

2021-02-11 20:11 UTC, sadasant commented on releases/2021-02/js.md
> +### AI Metrics Advisor
I have updated the headers to include Azure, and I have included your change here 🌞

2021-02-11 23:25 UTC, czubair approved these changes

2021-02-12 00:19 UTC, KarishmaGhiya commented on releases/2021-02/js.md
> +- Metrics Advisor is releasing support for Azure Active Directory Authentication and support to rotate the API and Subscription Keys.
I think I added more to this - 

```suggestion
- Metrics Advisor is releasing support for Azure Active Directory Authentication and support to rotate the API and Subscription Keys.

##### Breaking Changes in @azure/ai-metrics-advisor@1.0.0@beta.3
- Renamed a method `listDimensionValuesForDetectionConfig()` to `listAnomalyDimensionValues()`
- Changed the response types for update methods



```

2021-02-12 17:41 UTC, sadasant commented on releases/2021-02/js.md
> +- Metrics Advisor is releasing support for Azure Active Directory Authentication and support to rotate the API and Subscription Keys.
My bad! Thank you!

2021-02-12 18:25 UTC, sarangan12 approved these changes

2021-02-12 18:28 UTC, joheredi commented on releases/2021-02/js.md
> +- Azure Event Grid
```suggestion
- Azure Event Grid
- Azure Data Tables
```

2021-02-12 18:28 UTC, joheredi commented on releases/2021-02/js.md
> +$> npm install @azure/eventgrid@next
```suggestion
$> npm install @azure/eventgrid@next
$> npm install @azure/data-tables@next
```

2021-02-12 18:46 UTC, ramya-rao-a requested changes
I don't see Search here...

Can we do a check on whether our partners have released anything?
- Monitor
- Communications
- Digital twins
- Synapse
- Quantum
- Attestation

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- Added distributed tracing support. EventGridProducerClient will now create spans when sending events to Event Grid.
```suggestion
- Added distributed tracing support. `EventGridProducerClient` will now create spans when sending events to Event Grid.
```

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- Fixed an issue that the download stream returned by `BlobClient.download` won't release underlying resources unless it's fully consumed. [Issue #11850](https://github.com/Azure/azure-sdk-for-js/iss
Avoid giving out issue and PR links in the high level release notes. These are available in the changelog

```suggestion
- Fixed a compile time failure in resolving the crypto module in Angular projects which got introduced in a previous update. 
- Fixed an issue where the download stream returned by `BlobClient.download` method would not release underlying resources unless it's fully consumed.
```

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- Fixed a compile failure due to "Can't resolve 'crypto'" in Angular. [Issue #13267](https://github.com/Azure/azure-sdk-for-js/issues/13267).
Avoid giving out issue and PR links in the high level release notes. These are available in the changelog

```suggestion
- Fixed a compile time failure in resolving the crypto module in Angular projects which got introduced in a previous update.
```

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +##### Major Fixes in @azure/storage-blob@12.4.1 ([Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-blob/CHANGELOG.md#1241-2021-02-03))
Do we need the changelog link at this level? Wouldnt the changelog link a few lines above suffice?

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- Metrics Advisor is releasing support for Azure Active Directory Authentication and support to rotate the API and Subscription Keys.
```suggestion
- Metrics Advisor is releasing support for Azure Active Directory Authentication and the rotation of the API and Subscription Keys.
```

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- We are releasing a new  preview version for metrics advisor with AAD support feature
This should not be a bullet point

```suggestion
We are releasing a new  preview version for metrics advisor with AAD support feature
```

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- The 'keytar' dependency has been updated to the latest version.
A dependency update is not a release highlight unless it solved a major problem for the customer. I recall the user did have some trouble which required us to do this update. Mentioning that here would help

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- Fixed Azure Stack support for the NodeJS version of the `InteractiveBrowserCredential`.
Can we talk about what the problem before was? If I am an Azure Stack user, I wouldnt know whether this line would apply to me or not

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- In this beta we've updated `InteractiveBrowserCredential` to use the Auth Code Flow with PKCE rather than Implicit Grant Flow by default in the browser, to better support browsers with enhanced sec
Can we provide links for `Auth Code Flow with PKCE` and the `Implicit Grant flow`?

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- Backup and restore operations will now return a `BackupResult` and `RestoreResult` as appropriate.
What was it returning before? Does the user have to change their code? If this is not a breaking change or highly impacting, perhaps we can skip mentioning it?

The points under `Major Fixes on @azure/keyvault-admin@4.0.0-beta.2` do not seem to be developer impacting changes either. They do not need to react to these changes. I would recommend removing both the `Major Fixes` and this current section here and have say just this line

> The beta releases has bug fixes to improve quality and support for custom role definitions.

See [What is a developer impacting change?](https://github.com/Azure/azure-sdk/blob/08f279b39a4c19822b1509e6b10fc3ce256607b5/docs/policies/releasenotes.md#whats-a-developer-impacting-change)

cc @maorleger

2021-02-12 18:46 UTC, ramya-rao-a commented on releases/2021-02/js.md
> +- Fixes an issue where the `RetryMode` enum for use when setting the RetryOptions.mode field in `EventHubConsumerClientOptions` or `EventHubClientOptions` wasn't exported by the package.
I would skip this. User does not have to change anything unless they want to change the retry mode for which there were workarounds too. See [What is a developer impacting change?](https://github.com/Azure/azure-sdk/blob/08f279b39a4c19822b1509e6b10fc3ce256607b5/docs/policies/releasenotes.md#whats-a-developer-impacting-change)

cc @chradek

2021-02-12 18:48 UTC, sadasant commented
@ramya-rao-a @joheredi thank you for your feedback! I'll be working on an update ✌

2021-02-12 18:51 UTC, joheredi commented on releases/2021-02/js.md
> +- Added distributed tracing support. EventGridProducerClient will now create spans when sending events to Event Grid.
```suggestion
- Added distributed tracing support. EventGridProducerClient will now create spans when sending events to Event Grid.

### Azure Data Tables

We released a new beta package for the Data Tables service

#### @azure/data-tables [Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/tables/data-tables/CHANGELOG.md#100-beta3-2021-02-09)

##### Breaking changes in @azure/data-tables@1.0.0-beta.5

- Migrated from  Core V1 (`@azure/core-http`) to Core v2 (`@azure/core-https` & `@azure/core-client`). With this change, the response types no longer contain the raw response `_response`. To access the raw response, an `onResponse` callback has to be passed in the request options bag.

   ```typescript
   let createResult: FullOperationResponse  | undefined;
   await client.createEntity(testEntity, { onResponse: (response) => (createResult = response) });
   ```
```

2021-02-12 20:49 UTC, sadasant commented on releases/2021-02/js.md
> +##### Major Fixes in @azure/storage-blob@12.4.1 ([Changelog](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-blob/CHANGELOG.md#1241-2021-02-03))
We generally point to the exact version in the changelog above. In this case we have two, so I thought on separating them.

2021-02-12 20:51 UTC, sadasant commented on releases/2021-02/js.md
> +- Fixes an issue where the `RetryMode` enum for use when setting the RetryOptions.mode field in `EventHubConsumerClientOptions` or `EventHubClientOptions` wasn't exported by the package.
Removing it!

2021-02-12 20:54 UTC, sadasant commented on releases/2021-02/js.md
> +- Fixed Azure Stack support for the NodeJS version of the `InteractiveBrowserCredential`.
Thoughts on this?

> Fixed a bug that appeared while using `InteractiveBrowserCredential` to authenticate against Azure Stack from NodeJS (for local apps that would ask for authentication using a browser window). Azure Stack has specific authentication requirements that were missed on our previous `InteractiveBrowserCredential` release.

2021-02-12 20:57 UTC, sadasant commented on releases/2021-02/js.md
> +- The 'keytar' dependency has been updated to the latest version.
This is the original issue: https://github.com/Azure/azure-sdk-for-js/issues/13531

That issue is still open and the real solution is not trivial. This update helps but it's very minor. I'll remove the highlight entry.

2021-02-12 21:08 UTC, sadasant commented on releases/2021-02/js.md
> +- Backup and restore operations will now return a `BackupResult` and `RestoreResult` as appropriate.
It's a breaking change, but from one beta to another, since this client hasn't been GAd.

BackupResult and RestoreResult from backup/restore long running operations now contain additional information about the operation, we can say that 🤔

2021-02-12 21:13 UTC, sadasant commented on releases/2021-02/js.md
> +- In this beta we've updated `InteractiveBrowserCredential` to use the Auth Code Flow with PKCE rather than Implicit Grant Flow by default in the browser, to better support browsers with enhanced sec
Done here: https://github.com/Azure/azure-sdk/pull/2333/commits/7c801836c2799febab0274578673c4527cf86e6f

2021-02-12 21:14 UTC, sadasant commented on releases/2021-02/js.md
> +- Fixes an issue where the `RetryMode` enum for use when setting the RetryOptions.mode field in `EventHubConsumerClientOptions` or `EventHubClientOptions` wasn't exported by the package.
Removed it here: https://github.com/Azure/azure-sdk/pull/2333/commits/7c801836c2799febab0274578673c4527cf86e6f

2021-02-12 21:28 UTC, sadasant commented on releases/2021-02/js.md
> +- Added distributed tracing support. EventGridProducerClient will now create spans when sending events to Event Grid.
Pushed here: https://github.com/Azure/azure-sdk/pull/2333/files#diff-a1ff6f8d1225133bd78843c3c728c052d26119ab995b81106191195e06d295a4R214

2021-02-12 23:46 UTC, sadasant commented
@ramya-rao-a 

Regarding the missing highlights:

- Synapse (& Monitor) was left out because the update didn't seem relevant enough for a highlight when Jonathan and I reviewed the changes.
- Communications: I have contacted Dominik. to see if they can provide some highlights.
- Digital twins: I have contacted Zoltan.
- Quantum: I have contacted Victor.
- Attestation: I have contacted Larry.

2021-02-12 23:52 UTC, ramya-rao-a approved these changes
Please follow up with the missing highlights in a separate PR. We can merge this for now

2021-02-13 01:45 UTC, merged