Refining Android guidelines
Azure/azure-sdk pull request #2505
Opened 2021-03-04 02:29 UTC by vcolin7

- Added missing samples.
- Polished guidelines to resemble the ones for Java where it made sense.
- Resolved many TODOs.

> NOTE: There are still some pending TODOs and discussions I want to resolve, but I think opening this draft PR is a good place to start to get some feedback :)

2021-04-21 19:52 UTC, vcolin7 commented
/azp run azure-sdk - ci

2021-05-05 05:37 UTC, JonathanGiles requested changes

2021-05-05 05:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/SHOULD id="android-service-client-feature-support" %} support only those features provided by the Azure service that would make sense for a mobile app would access. Mobile apps
A few comments:

1) Typo on "support only those features provided by the Azure service that would make sense for a mobile app would access."

2) I don't know what you mean by "Mobile apps are inherently consumer applications". If you're saying that most Android apps that would use Azure are generally targeted at the general population, and not targeted at business users - I am not sure we have the data to back that up.

2021-05-05 05:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-async-rxjava" %} additionally provide a separate library containing an RxJava-based async client containing all service methods. The RxJava-based API must be c
This isn't part of the plan for now.

2021-05-05 05:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-client-options-classes-extend" %} make `Options` objects used when initializing a service client extend from Azure Core's `ClientOptions` class.
I don't understand this guidance. Why are we doing this rather than just have client configuration be first-level configuration settings in the Builder? This deviates from Java and I'm not sure what the purpose of it is.

2021-05-05 05:37 UTC, JonathanGiles commented on docs/android/design.md
> +public enum ConfigurationApiVersion implements ApiVersion {
Use `ServiceVersion`, not `ApiVersion`, to be consistent with Java

2021-05-05 05:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-required-and-optional-method-parameters" %} accept all arguments required to or execute a method call as individual parameters to the method. An argument is co
typo: "accept all arguments required to or execute a method call"

2021-05-05 05:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-required-and-optional-method-parameters" %} accept all arguments required to or execute a method call as individual parameters to the method. An argument is co
I'm not sure what you're saying with the second sentence - is it necessary?

2021-05-05 05:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-models-interface" %} put model classes that are intended as service return types only, and which have undesirable public API into the `.implementation.models`
Presumably the Android guidance is to use 'internal' rather than 'implementation' (even though I prefer implementation).

2021-05-05 05:37 UTC, JonathanGiles commented on docs/android/design.md
> +Examples of situations where this is applicable include when there are constructors or setters on a type which receive implementation types, or when a type should be immutable but needs to be mutable
implementation / internal

2021-05-05 05:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-enums-future-growth" %} use `ExpandableStringEnum` provided by Azure Core for enumerations if the values are known to expand in future.
This guidance is confusing because it suggests to use `enum` and `TypeDef` for the same use case? My preference would be to use enum wherever applicable, which, as it turns out, is almost nowhere and `ExpandableStringEnum` is by far the default pattern to be used in most cases.

2021-05-05 18:29 UTC, anuchandy commented on docs/android/design.md
> +{% include requirement/MUST id="android-models-interface" %} put model classes that are intended as service return types only, and which have undesirable public API into the `.implementation.models`
I also prefer `implementation`, it really simplifies the reuse of existing tools such as doc, code quality tools and apiView.

2021-05-05 18:34 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/SHOULD id="android-service-client-feature-support" %} support only those features provided by the Azure service that would make sense for a mobile app would access. Mobile apps
For point no. 2 what I mean to say is that mobile apps are, for the most part, directly user facing, as opposed to middleware or backend software. I can rephrase to avoid confusion.

2021-05-05 18:35 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-async-rxjava" %} additionally provide a separate library containing an RxJava-based async client containing all service methods. The RxJava-based API must be c
You mean the Rx-based separate clients or even the use of CompletableFuture?

2021-05-05 18:41 UTC, vcolin7 commented on docs/android/design.md
> +public enum ConfigurationApiVersion implements ApiVersion {
Do we want to deviate from iOS in this case then? Would we want them to follow in naming this `ServiceVersion`?

2021-05-05 18:44 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-required-and-optional-method-parameters" %} accept all arguments required to or execute a method call as individual parameters to the method. An argument is co
We are trying to give some lenience in what can be considered a required argument. Some arguments that might not be literally declared as "required" in the swagger specification might still be present in most common use cases and thus could be considered important to have as individual parameters in some APIs instead of being put in an options bag.

2021-05-05 18:46 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-models-interface" %} put model classes that are intended as service return types only, and which have undesirable public API into the `.implementation.models`
I know we talked about this for a while and found that a few public libraries use `internal`, although I don't think it's necessarily considered a widespread practice and moreso something of a preference up to the developer. I think Anu's point has some weight as well. I'll revisit some public and widely used libraries to see what name they are using.

2021-05-05 19:00 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-async-rxjava" %} additionally provide a separate library containing an RxJava-based async client containing all service methods. The RxJava-based API must be c
Rx clients

2021-05-05 19:08 UTC, JonathanGiles commented on docs/android/design.md
> +public enum ConfigurationApiVersion implements ApiVersion {
ios can do what they want. In Java we've gone with serviceVersion so it would be consistent with that, imho.

2021-05-05 19:08 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-enums-future-growth" %} use `ExpandableStringEnum` provided by Azure Core for enumerations if the values are known to expand in future.
This was first added based on some old documentation saying `enum` was not recommended for Android for performance reasons. Having said that, it looks like this [has not been the case for a while](https://stackoverflow.com/a/4822906/4967034). We can just use `enum` it seems.

2021-05-05 19:13 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-required-and-optional-method-parameters" %} accept all arguments required to or execute a method call as individual parameters to the method. An argument is co
This is the truth regardless though, right? We are building convenience layers that will have extra API and extra parameters. This feels like it doesn't give enough clarity to readers.

2021-05-05 19:15 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-models-interface" %} put model classes that are intended as service return types only, and which have undesirable public API into the `.implementation.models`
I would strongly prefer implementation for exactly the reason Anu shares - APIView, checkstyle, etc are all configured already with knowledge of the implementation special case.

2021-05-05 21:32 UTC, vcolin7 commented on docs/android/design.md
> +public enum ConfigurationApiVersion implements ApiVersion {
Also, is there a reason why .NET and Java use `ServiceVersion` but Python uses `ApiVersion`?

2021-05-05 22:36 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-client-options-classes-extend" %} make `Options` objects used when initializing a service client extend from Azure Core's `ClientOptions` class.
The concept for this class came before we adopted the builder pattern from Java and is more aligned to what we do in iOS. We can fully follow what Java does here but I have a question about it: what purpose does the `ClientOptions` class serve in Java and why were its members (applicationId, headers) not settable on builders directly but on the options bag itself? Also, is there a specific reason Java's `ClientOptions` is not final? Are we expecting to extend from it so service-specific options are passed to builders through children classes?

2021-05-05 22:37 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-async-rxjava" %} additionally provide a separate library containing an RxJava-based async client containing all service methods. The RxJava-based API must be c
We can end up adding something like this for cases where the service requires capabilities that Rx or callbacks allow for and that are lacking in `CompletableFuture`.

```suggestion
If you think your business scenario would be better suited for an RxJava or callback-based SDK as opposed to one based on `CompletableFuture`, please contact the [Azure SDK Architecture Board][Architecture Board] for guidance.
```

2021-05-05 22:38 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/SHOULD id="android-service-client-feature-support" %} support only those features provided by the Azure service that would make sense for a mobile app would access. Mobile apps
What about this?

```suggestion
{% include requirement/SHOULD id="android-service-client-feature-support" %} support only those features provided by the Azure service that would make sense for a mobile app would access. Mobile apps are inherently end user-facing applications, and only a subset of Azure services and features are intended for use by these type of applications. While completeness is valuable and gaps in functionality can cause frustration, a smaller binary size and an opinionated stance of only providing end user-facing functionality will make our libraries easier and more desirable for app developers to use.
```

2021-05-05 22:42 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-async-rxjava" %} additionally provide a separate library containing an RxJava-based async client containing all service methods. The RxJava-based API must be c
I wouldn't include that - it invites requests to be different. Let people try with CF first.

2021-05-05 22:46 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-client-options-classes-extend" %} make `Options` objects used when initializing a service client extend from Azure Core's `ClientOptions` class.
ClientOptions is a bundle to pass down to the **HTTP client and pipeline**. If it were individually set values, we would need to bundle them up internally, and users would need to set more properties for each builder, rather than create their single ClientOptions instance that they can reuse. It's not final so users can subclass if they want to support custom http clients / pipelines. It is not intended for service specific options.

2021-05-05 22:47 UTC, JonathanGiles commented on docs/android/design.md
> +public enum ConfigurationApiVersion implements ApiVersion {
No, architect preference basically.

2021-05-05 22:47 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-enums-future-growth" %} use `ExpandableStringEnum` provided by Azure Core for enumerations if the values are known to expand in future.
Just be clear that enum is much less preferred than ExpandableStringEnum though.

2021-05-06 01:16 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-required-and-optional-method-parameters" %} accept all arguments required to or execute a method call as individual parameters to the method. An argument is co
Are you saying that by being too specific we might cast doubt on an otherwise common assumption/reasoning? I think that is possible in some cases but I can't see how it is confusing here (which doesn't mean I'm opposed to removing it, I'm just curious as to why it caught your attention).

2021-05-06 01:21 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-required-and-optional-method-parameters" %} accept all arguments required to or execute a method call as individual parameters to the method. An argument is co
In your first sentence you say "accept all arguments required". In your second sentence you are redefining "required" to mean "if the library author deems it to be essential to the developer experience of the client API, regardless of whether the argument is flagged as required in the service's API spec". This is incorrect - something is required if the service requires it. It could also be required if the API designer thinks it is required. Your second sentence takes away the requirement that service-dictated requirements are real. By saying more, you've incorrectly redefined something - so this is a good case where saying less improves clarity.

2021-05-06 02:30 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-client-options-classes-extend" %} make `Options` objects used when initializing a service client extend from Azure Core's `ClientOptions` class.
Ok, so we will be passing optional service-related parameters to a builder via fluent APIs instead of using a single options bag. Having said that, I think we can still make use of [the design we had for `ClientOptions`](https://github.com/Azure/azure-sdk-for-android/blob/azure-core_1.0.0-beta.3/sdk/core/azure-core/src/main/java/com/azure/android/core/http/options/ClientOptions.java) for passing some non-service-related parameters to a builder. What do you think?

2021-05-06 02:34 UTC, vcolin7 commented
@JonathanGiles Something that came to mind considering the `ClientOptions` and `ServiceVersion` vs `ApiVersion` conversations below, along with some changes made when breaking up Core into smaller modules, is that I feel like we are aligning a lot more with decisions made for the Java SDKs than with iOS as a conjoined mobile offering.

Originally, we tried to have a unified approach between both mobile SDKs in the design of some of these components, so diverging later on to be closer to Java makes me fear we will end up looking much different from iOS in places where some choices don't seem obvious for Android but rather made merely because that's what Java did already.

While it's true that some Java developers end up venturing into the mobile world, it is also a reality that some companies develop solutions for both iOS and Android in parallel or one after the other using the same team or part of it. I don't have enough data to know which scenario is more common, but based on testimonies we gathered in the past I'm inclined to think it's the latter.

What I'm trying to say is that I think there is value in some design decisions made together with iOS and that we should consider keeping them in the conversation in the road to GA.

2021-05-06 03:08 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-required-and-optional-method-parameters" %} accept all arguments required to or execute a method call as individual parameters to the method. An argument is co
I see what you mean, the idea behind what I wrote is exactly the one you portrayed in just now: that both arguments flagged as "required" in the service spec and those the API designer considers required, should be treated equally for the purpose of being put in API signatures. That said, this does not mean that a designer can "downgrade" an argument that is "required" in the service spec to "optional", which could be an interpretation of the second sentence.

What do you think of something like the following?

```suggestion
{% include requirement/MUST id="android-required-and-optional-method-parameters" %} accept all arguments required to or execute a method call as individual parameters to the method. An argument is considered required if it is flagged as such in the service's API spec or if the library author deems it to be essential to the developer experience of the client API.
```

2021-06-30 21:20 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-client-options-classes-extend" %} make `Options` objects used when initializing a service client extend from Azure Core's `ClientOptions` class.
Ended up removing this ability for the time being.

2021-06-30 22:03 UTC, JonathanGiles approved these changes

2021-06-30 22:04 UTC, merged