[March Release] Adding Event Hubs Info
Azure/azure-sdk pull request #2524
Opened 2021-03-09 18:29 UTC by jsquire

# Summary

The focus of these changes is to add information for the Event Hubs packages that were released for the March milestone.

# Last Upstream Rebase

Tuesday, March 9, 1:15pm (EST)

2021-03-09 19:32 UTC, christothes approved these changes

2021-03-09 22:04 UTC, weshaggard requested changes
Lets try to use https://github.com/Azure/azure-sdk/pull/2502 for collecting these.

2021-03-09 22:13 UTC, jsquire commented
> Lets try to use #2502 for collecting these.

The script still requires manual clean-up for the change logs of each service to adapt the verbose changelog to the release notes.   I'm fine deferring to @Mohit-Chakraborty  release manager for a central run and rescoping this PR to fix the text after.

2021-03-10 13:14 UTC, jsquire commented
> If there are any manual clean-up feel free to update the PR with those changes. The entire goal is to try and see what, if any, those changes are so we can start to tweak and improve the process.

Understood.  I was just noting that I don't want to step on the release manager's toes and pull the script run into this PR.   Once that's run, I'll rescope to update here or fold these changes in.  I'm leaving this open in the meantime to remind me.

2021-03-10 19:02 UTC, weshaggard commented
It looks like our automation already pulled in the eventhubs changes in to https://github.com/Azure/azure-sdk/pull/2502 so please have a look over it and if it matches what you want great there is nothing to do. If it needs some tweaks you can go ahead and push a commit to that PR with those tweaks.

2021-03-10 19:05 UTC, jsquire commented
> It looks like our automation already pulled in the eventhubs changes in to #2502 so please have a look over it and if it matches what you want great there is nothing to do. If it needs some tweaks you can go ahead and push a commit to that PR with those tweaks.

oh!  my bad.  I'm guilty of assuming the PR that you linked was the script;  I didn't click through to see you were sharing generated doc.  Thanks, @weshaggard, and apologies for the confusion.

2021-03-10 20:15 UTC, jsquire commented
Closing this out;  changes have been suggested on #2502.

2021-03-10 20:15 UTC, closed without merging