[ServiceBus] March release notes
Azure/azure-sdk pull request #2531
Opened 2021-03-09 20:30 UTC by yunhaoling

2021-03-09 20:49 UTC, swathipil approved these changes

2021-03-09 21:00 UTC, xiangyan99 commented on releases/2021-03/python.md
> +pip install azure-servicebus
# ($> pip install ${PackageName}==${PackageVersion})

2021-03-09 21:01 UTC, xiangyan99 commented on releases/2021-03/python.md
> +### Service Bus 7.1.0 [Changelog](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/CHANGELOG.md#710-2021-03-09)
Please pin to the release tag rather than using master

2021-03-09 21:08 UTC, yunhaoling commented on releases/2021-03/python.md
> +### Service Bus 7.1.0 [Changelog](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/CHANGELOG.md#710-2021-03-09)
thanks for calling it out! just updated

2021-03-09 22:00 UTC, xiangyan99 approved these changes

2021-03-09 22:00 UTC, weshaggard requested changes
Lets try to use https://github.com/Azure/azure-sdk/pull/2503 for the python changelogs.

2021-03-16 20:44 UTC, xiangyan99 commented
Updated in #2503

2021-03-16 20:44 UTC, closed without merging