Update ios.md
Azure/azure-sdk pull request #2549
Opened 2021-03-11 04:58 UTC by jorgegarchirota

Add ACS release notes for iOS

2021-03-11 05:00 UTC, jorgegarchirota commented
@RezaJooyandeh , @ankitarorabit  if you can take a look into the iOS release notes

2021-03-11 05:33 UTC, JoshuaLai commented on releases/2021-03/ios.md
> +        .package(url: "https://github.com/Azure/azure-sdk-for-ios.git", from: "1.0.0-beta.8")
Is this beta 8 or beta 9?

2021-03-11 17:00 UTC, JoshuaLai approved these changes
lgtm

2021-03-11 17:18 UTC, tjprescott requested changes
Some template boilerplate needs to be removed, but thanks for creating this!

2021-03-11 17:18 UTC, tjprescott commented on releases/2021-03/ios.md
>  - _Add packages_
This line should be removed

2021-03-11 17:18 UTC, tjprescott commented on releases/2021-03/ios.md
>  #### _Package name_
These lines should be removed

2021-03-11 23:56 UTC, jorgegarchirota reviewed
The changes requested were addressed

2021-03-12 15:03 UTC, tjprescott approved these changes

2021-03-12 15:04 UTC, tjprescott commented
@czubair if this looks okay to you it should be ready to merge.

2021-03-12 21:48 UTC, RezaJooyandeh commented on releases/2021-03/ios.md
> +- `CommunicationIdentifierModel` and `CommunicationIdentifierSerializer` are no longer part of the communication package, they have been moved to AzureCommunicationChat
I do not think we should even mention where they are moved. These two types are not for developers to use. Should we say that they are removed from Azure Communication?

2021-03-12 21:49 UTC, RezaJooyandeh commented on releases/2021-03/ios.md
> +- Introduction of  a new struct `CommunicationIdentifierModel` to repesent a union type that is either a `communicationUser`, `phoneNumber`, or `microsoftTeamsUser`.
Let's omit that. This is not a feature for developers.

2021-03-13 03:51 UTC, jorgegarchirota commented on releases/2021-03/ios.md
> +- `CommunicationIdentifierModel` and `CommunicationIdentifierSerializer` are no longer part of the communication package, they have been moved to AzureCommunicationChat
@RezaJooyandeh  I update the docs ;)

2021-03-13 03:54 UTC, jorgegarchirota reviewed
The changes requested were addressed

2021-03-15 21:53 UTC, RezaJooyandeh approved these changes

2021-03-15 21:56 UTC, merged