Move the replace notes into the replace column in csv
Azure/azure-sdk pull request #2642
Opened 2021-04-01 03:00 UTC by v-xuto

About the second PR:

- Move the replace notes column values to the new Replace column. If there are multiple values, then delimit them with a comma.

@jongio , @weshaggard for notification.

2021-04-01 15:55 UTC, weshaggard commented on _data/releases/latest/java-packages.csv
> +"azure-storage-blob","com.microsoft.azure","11.0.1","","Storage - Blobs","Storage","https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/microsoft-azure-storage-blob","","NA","client",
@jongio this is a case where there is a version included. Did you want to keep the version. This one is also an interesting case because the package in Java is actually the artifact name and thus the old and new library share the same artifact name but only differ by groupId.

2021-04-01 15:56 UTC, weshaggard commented on _data/releases/latest/python-packages.csv
> +"azure-storage-file-share","12.4.1","","Storage - Files Shares","Storage","storage","","","client","true","","12/04/2019","active","","azure-storage-file 2.1.0",""
This is another case with a version in python and in this case I'm not sure we should include the version but I think it is going to come down to how we end up displaying these.

2021-04-01 15:57 UTC, weshaggard commented
@jongio I'll let you decide what we should do with the version number info as well as the java issue. My suggestion would be to only include information when the packages are different and include enough information to be able to link to the separate package.

2021-04-01 21:13 UTC, jongio requested changes

2021-04-01 21:13 UTC, jongio commented on _data/releases/latest/java-packages.csv
> +"azure-storage-blob","com.microsoft.azure","11.0.1","","Storage - Blobs","Storage","https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/microsoft-azure-storage-blob","","NA","client",
We can link to the package root without version number.  The user will assume the latest version is the best one to use.

Please update the CSVs in this format.  Delimit with comma if there are multiple packages.
 
Android & Java
 - GroupId/Package

.NET & JS & Python
 - Package

2021-04-02 15:56 UTC, weshaggard commented on _data/releases/latest/js-packages.csv
> +"@azure/eventgrid","4.1.0","","Event Grid","Event Grid","https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/eventgrid/eventgrid","","","client","true","","12/04/2019","","","@azure/eventgrid",
We should decide if we actually want to list the same package in the Replace column. @jongio for this case I'd suggest we just remove it.

2021-04-02 15:57 UTC, weshaggard commented on _data/releases/latest/python-packages.csv
> +"azure-eventgrid","1.3.0","","Event Grid","Event Grid","eventgrid","","","client","false","","","active","true","azure-eventgrid",""
Another case were we should probably remove the Replace as it is the same package.

2021-04-02 15:57 UTC, weshaggard approved these changes

2021-04-02 16:41 UTC, merged