Update hide column about IoT packages in csv files
Azure/azure-sdk pull request #2723
Opened 2021-04-14 06:43 UTC by v-xuto

1. Update hide column about IoT packages in CSV files by email CSV Updates.
2. Update the display name of the package  `Azure.Iot.DeviceUpdate` and  `Azure.Iot.ModelsRepository`  in four languages.

@jongio for notification.

2021-04-14 13:23 UTC, jongio commented
I added elena  @tzhanl 

LGTM

2021-04-14 16:50 UTC, weshaggard commented on _data/releases/latest/java-packages.csv
> +"iot-deps","com.microsoft.azure.sdk.iot","0.11.2","","IoT Deps","IoT","NA","NA","NA","client","false","","","","false","",""
@elraikhm Did we intend to unhide these packages?

2021-04-15 16:53 UTC, elraikhm commented on _data/releases/latest/java-packages.csv
> +"azure-iot-deviceupdate","com.azure","","1.0.0-beta.1","IoT Device Update","IoT Device Update","deviceupdate","","","client","true","","","","true","",""
Let's not hide it for now

2021-04-15 16:55 UTC, elraikhm commented on _data/releases/latest/java-packages.csv
> +"iot-deps","com.microsoft.azure.sdk.iot","0.11.2","","IoT Deps","IoT","NA","NA","NA","client","false","","","","false","",""
IoT team say this one is active

2021-04-15 17:26 UTC, elraikhm requested changes

2021-04-15 17:26 UTC, elraikhm commented on _data/releases/latest/java-packages.csv
> +"iot-deps-preview","com.microsoft.azure.sdk.iot","1.1.0","","IoT Deps","IoT","NA","NA","NA","client","false","","","","false","",""
Following packages should be hidden (set Hide to true)
iot-deps-preview | com.microsoft.azure.sdk.iot | 1.1.0
iot-deps-serializer | com.microsoft.azure | 0.3.3
iot-deps-serializer | com.microsoft.azure.sdk.iot.deps | 0.7.6
iot-device-client | com.microsoft.azure | 1.1.24
iot-device-client-preview | com.microsoft.azure.sdk.iot | 1.2.0

2021-04-15 17:26 UTC, elraikhm commented on _data/releases/latest/java-packages.csv
> +"iot-service-client-preview","com.microsoft.azure.sdk.iot","1.2.0","","IoT Service Client","IoT","NA","https://docs.microsoft.com/java/api/overview/azure/iot","NA","client","false","","","","false","
Hide = true for iot-service-client-preview | com.microsoft.azure.sdk.iot

2021-04-15 17:26 UTC, elraikhm commented on _data/releases/latest/java-packages.csv
> +"iot-service-client","com.microsoft.azure","1.2.18","","IoT Service Client","IoT","NA","https://docs.microsoft.com/java/api/overview/azure/iot","NA","client","false","","","","false","",""
iot-service-client | com.microsoft.azure | 1.2.18 should be hidden

2021-04-15 17:26 UTC, elraikhm commented on _data/releases/latest/java-packages.csv
> +"iot-deps","com.microsoft.azure.sdk.iot","0.11.2","","IoT Deps","IoT","NA","NA","NA","client","false","","","","false","",""
I mean the iot-deps | com.microsoft.azure.sdk.iot

2021-04-15 17:26 UTC, elraikhm commented on _data/releases/latest/python-packages.csv
> +"azure-servicemanagement-legacy","0.20.7","","Service Management - Legacy","Core","core","NA","NA","mgmt","false","","","community","","",""
Support should be "Active" for
iothub-client | 1.1.2.0
iothub-service-client | 1.1.0.0

2021-04-16 02:25 UTC, v-xuto commented on _data/releases/latest/java-packages.csv
> +"azure-iot-deviceupdate","com.azure","","1.0.0-beta.1","IoT Device Update","IoT Device Update","deviceupdate","","","client","true","","","","true","",""
@elraikhm - I have updated based on the comments.

2021-04-16 02:26 UTC, v-xuto commented on _data/releases/latest/java-packages.csv
> +"iot-deps-preview","com.microsoft.azure.sdk.iot","1.1.0","","IoT Deps","IoT","NA","NA","NA","client","false","","","","false","",""
@elraikhm - I have updated based on the comments.

2021-04-16 02:26 UTC, v-xuto commented on _data/releases/latest/java-packages.csv
> +"iot-service-client-preview","com.microsoft.azure.sdk.iot","1.2.0","","IoT Service Client","IoT","NA","https://docs.microsoft.com/java/api/overview/azure/iot","NA","client","false","","","","false","
@elraikhm - I have updated based on the comments.

2021-04-16 02:27 UTC, v-xuto commented on _data/releases/latest/java-packages.csv
> +"iot-service-client","com.microsoft.azure","1.2.18","","IoT Service Client","IoT","NA","https://docs.microsoft.com/java/api/overview/azure/iot","NA","client","false","","","","false","",""
@elraikhm - I have updated based on the comments.

2021-04-16 02:27 UTC, v-xuto commented on _data/releases/latest/python-packages.csv
> +"azure-servicemanagement-legacy","0.20.7","","Service Management - Legacy","Core","core","NA","NA","mgmt","false","","","community","","",""
@elraikhm - I have updated based on the comments.

2021-04-25 06:39 UTC, v-xuto commented
@elraikhm, @weshaggard -  I have updated according to your comments. If there is no problem, please help merge it.

2021-04-26 17:07 UTC, weshaggard approved these changes

2021-04-26 17:07 UTC, weshaggard commented
@elhorton I'm going ahead and merging this PR as it looks reasonable to me and these PR's are hard to keep updated. If there are other changes we can file another PR.

2021-04-26 17:08 UTC, merged