Mobile release notes for May 2021
Azure/azure-sdk pull request #2845
Opened 2021-05-13 20:24 UTC by vcolin7

2021-05-13 20:31 UTC, tjprescott requested changes

2021-05-13 20:31 UTC, tjprescott commented on releases/2021-05/ios.md
> +- Azure Communication Services Common
```suggestion
- Azure Communication Services Common
- Azure Communication Services Calling
```

2021-05-13 20:31 UTC, tjprescott commented on releases/2021-05/ios.md
> +- Removed following classes:  `CreateChatThreadResult`, `CreateChatThreadRequest`, `ChatMessage`, `ChatMessageContent`, `ChatParticipant`, `ChatMessageReadReceipt`, `ChatThreadProperties`.
Chat did not release as beta 12. It only released as Beta 11 on Apr 7th. If that was in the last release notes, it can be omitted from these.

2021-05-13 20:31 UTC, tjprescott commented on releases/2021-05/ios.md
> +
Should we call out:
```
#### Features

General availability release.
```

For Common and Calling?

2021-05-13 20:33 UTC, vcolin7 commented on releases/2021-05/ios.md
> +
It's called out at the top under the `GA` section, but maybe we can be more explicit about it. Any thoughts @czubair?

2021-05-13 20:34 UTC, vcolin7 commented on releases/2021-05/ios.md
> +- Removed following classes:  `CreateChatThreadResult`, `CreateChatThreadRequest`, `ChatMessage`, `ChatMessageContent`, `ChatParticipant`, `ChatMessageReadReceipt`, `ChatThreadProperties`.
I see, I thought they ahd released because the CHANGELOG has a release date. I can remove it from these notes then.

2021-05-14 18:47 UTC, tjprescott commented on releases/2021-05/ios.md
> +- Removed following classes:  `CreateChatThreadResult`, `CreateChatThreadRequest`, `ChatMessage`, `ChatMessageContent`, `ChatParticipant`, `ChatMessageReadReceipt`, `ChatThreadProperties`.
They were going to but then changed their minds.

2021-05-14 18:47 UTC, tjprescott approved these changes

2021-05-17 18:05 UTC, merged