[go-guideline] Pagers aren't supposed to be interfaces.
Azure/azure-sdk pull request #3596
Opened 2021-11-10 22:42 UTC by richardpark-msft

As per conversation with @jhendrixmsft, Pagers are not supposed to be interfaces.

2021-11-10 22:45 UTC, jhendrixMSFT commented on docs/golang/introduction.md
> +{% include requirement/MUST id="golang-pagination-pagers" %} create Pager interface compatible types with the name `<Resource>Pager` that are to be returned from their respective operations.
This could be reworked a bit to drop the word "interface".  Maybe something like "create Pager types with the name..."

2021-11-10 22:46 UTC, jhendrixMSFT requested changes
A few minor things.  While we're mucking about here, could you please make the same change to Pollers?

2021-11-10 22:46 UTC, jhendrixMSFT commented on docs/golang/introduction.md
>  {% include requirement/MUST id="golang-pagination-pagers-interface-page" %} expose methods `NextPage()`, `PageResponse()`, and `Err()` on the `<Resource>Pager` type.
We should also add a blurb stating that the pager MUST NOT export an fields.

2021-11-10 23:04 UTC, JeffreyRichter approved these changes

2021-11-10 23:04 UTC, JeffreyRichter commented on docs/golang/introduction.md
> +{% include requirement/MUST id="golang-pagination-pagers" %} create Pager interface compatible types with the name `<Resource>Pager` that are to be returned from their respective operations.
This will need re-work for generics

2021-11-10 23:04 UTC, JeffreyRichter commented on docs/golang/introduction.md
>  {% include requirement/MUST id="golang-pagination-pagers-interface-page" %} expose methods `NextPage()`, `PageResponse()`, and `Err()` on the `<Resource>Pager` type.
Pages do need to return CurrentPageToken an NextPageToken. These could be string fields or methods.

2021-11-12 18:23 UTC, richardpark-msft commented on docs/golang/introduction.md
>  {% include requirement/MUST id="golang-pagination-pagers-interface-page" %} expose methods `NextPage()`, `PageResponse()`, and `Err()` on the `<Resource>Pager` type.
We should probably settle on a method, just to keep things flexible for the future.

2021-11-12 18:24 UTC, richardpark-msft commented on docs/golang/introduction.md
> +{% include requirement/MUST id="golang-pagination-pagers" %} create Pager interface compatible types with the name `<Resource>Pager` that are to be returned from their respective operations.
Yeah, I was realizing that yesterday. It's probably still worth doing this doc update (once I incorporate feedback) just to eliminate any possibility of people thinking interfaces can be part of the public surface (at least, here)

2022-03-01 23:25 UTC, closed without merging

2022-03-01 23:25 UTC, richardpark-msft commented
(@jhendrixMSFT is making changes in this area now, so I'm fairly certain what I had here is outdated. We'll revisit and update after that design is complete)