adding section 5 on legacy package management
Azure/azure-sdk pull request #4092
Opened 2022-03-25 22:34 UTC by mario-guerra

2022-03-25 22:38 UTC, mario-guerra commented
This is a redo of a [PR](https://github.com/Azure/azure-sdk/pull/2123) that Elena was working on before she left. Updated Section 5 of the package deprecation guidelines to match our [wiki content](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/377/Managing-Packages-for-an-SDK-Release).

2022-03-25 22:41 UTC, mario-guerra commented
Added language leads as reviewers.

2022-03-29 17:45 UTC, RickWinter reviewed
LGTM for Go

2022-04-07 20:55 UTC, jsquire approved these changes
.NET looks good.     I left a few minor thoughts on formatting and wording.

2022-04-07 20:55 UTC, jsquire commented on docs/policies/releases.md
> +Please note, this package has been deprecated. A replacement package is available [package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly encourage you to upgrade to continue
```suggestion
Please note, this package has been deprecated. A replacement package is available [package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly encourage you to upgrade to continue receiving updates. See the [Migration Guide](https://dummylink.com/) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

Not sure if "the" or "its" makes more sense in this context, but it reads a bit awkwardly to me without something there.

2022-04-07 20:55 UTC, jsquire commented on docs/policies/releases.md
> +```markdown
Should we consider wrapping these markdown snippets for readability, or are we aiming for the "just copy/paste" scenario?

2022-04-07 20:55 UTC, jsquire commented on docs/policies/releases.md
> +Note, you can search for sample repositories under https://docs.microsoft.com/en-us/samples/browse/?products=azure
```suggestion
Note, you can search for sample repositories under https://docs.microsoft.com/samples/browse/?products=azure.
```

2022-04-07 20:55 UTC, jsquire commented on docs/policies/releases.md
> +-	Update package index files to identify legacy packages replacement
```suggestion
-	Update package index files to identify legacy packages replacement.
```

Most of the other bullets have punctuation.  Should we consider adding it here?

2022-04-07 20:55 UTC, jsquire commented on docs/policies/releases.md
> +-	Make updates to the legacy packages in the package manager. Use the following message and follow programming language instructions
```suggestion
-	Make updates to the legacy packages in the package manager. Use the following message and follow programming language instructions.
```

2022-04-07 20:55 UTC, jsquire commented on docs/policies/releases.md
> +-	If you are deprecating a package version, but staying within the same package name, update the wording above to mention a specific version
```suggestion
-	If you are deprecating a package version, but staying within the same package name, update the wording above to mention a specific version.
```

2022-04-07 20:55 UTC, jsquire commented on docs/policies/releases.md
> +  |
```suggestion
```

2022-04-07 21:10 UTC, mario-guerra commented on docs/policies/releases.md
> +```markdown
I would wrap but I'm not aware of a way to do word wrap in markdown and Google was no help. Do you know how to specify wrapping for markdown snippets?

2022-04-07 21:23 UTC, xirzec approved these changes
Thanks for driving this!

I left a few minor remarks, but it looks good from the JS side!

2022-04-07 21:23 UTC, xirzec commented on docs/policies/releases.md
> +-	Note, we cannot deprecate GA libraries which were released less than 1 year ago per the [current Azure SLA](https://www.microsoft.com/LICENSING/PRODUCT-LICENSING/PRODUCTS)
nit:maybe something like `*Note:*` would make this more scannable? - it's a little unclear why the third bullet isn't a "note" and what the distinction between them is

2022-04-07 21:23 UTC, xirzec commented on docs/policies/releases.md
> +-	Once a library has been identified as suitable for replacement, initiate a request to have NuGet search popularity for the legacy library forwarded to the new library. The SDK team engineering team
this point seems rather .NET specific?

2022-04-07 21:23 UTC, xirzec commented on docs/policies/releases.md
> +Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to version [version number] or abov
We try to avoid saying the "upgrade to version X" part in JS because we might need to deprecate releases later for security purposes, which would cause developers to follow a chain of "this is deprecated, go here" - instead we usually say something like "use the latest version" (latest being a special tag in npm)

2022-04-07 21:23 UTC, xirzec commented on docs/policies/releases.md
> +TS/JS | Run the command `npm deprecate` which takes the package name and the deprecation message.
We don't actually use the command directly, we run a build pipeline at https://dev.azure.com/azure-sdk/internal/_build?definitionId=2067

2022-04-07 21:46 UTC, lmazuel commented on docs/policies/releases.md
> +Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to version [version number] or abov
It's a risky wording, we don't plan to support older minor versions. For example, let's say 1.5 is the latest track1 of a package, and 1.6 to 1.8 are the track2. I don't want to write that I don't support below 1.5, which seems to imply we support 1.6, 1.7 and 1.8. Unless critical bug fixes (which never happened in this team as far as I know), we will always recommend people to move to the latest version first.

2022-04-07 21:53 UTC, lmazuel commented on docs/policies/releases.md
> +-	Make updates to the legacy packages in the package manager. Use the following message and follow programming language instructions.
If not a new package, Python will not update old releases with a message, so it's not possible without re-releasing all old packages in all versions.

2022-04-07 21:53 UTC, lmazuel commented on docs/policies/releases.md
> +Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to version [version number] or abov
Same in Python

2022-04-07 21:55 UTC, lmazuel commented on docs/policies/releases.md
> +Python | Publish an update to the package after updating the README.
For clarity, we can only update the latest release, we can't update past releases. It's implicit in Python that people should use the latest, and not expect support in previous minor.

2022-04-08 16:43 UTC, mario-guerra commented on docs/policies/releases.md
> +-	Note, we cannot deprecate GA libraries which were released less than 1 year ago per the [current Azure SLA](https://www.microsoft.com/LICENSING/PRODUCT-LICENSING/PRODUCTS)
```suggestion
-	**Note:** we cannot deprecate GA libraries which were released less than 1 year ago per the [current Azure SLA](https://www.microsoft.com/LICENSING/PRODUCT-LICENSING/PRODUCTS)
```

2022-04-08 16:44 UTC, mario-guerra commented on docs/policies/releases.md
> +-	Once a library has been identified as suitable for replacement, initiate a request to have NuGet search popularity for the legacy library forwarded to the new library. The SDK team engineering team
```suggestion
-	For .NET, once a library has been identified as suitable for replacement, initiate a request to have NuGet search popularity for the legacy library forwarded to the new library. The SDK team engineering team will know how to do this or who to talk to.
```

2022-04-08 16:47 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to version [version number] or abov
That's a good point, is it preferable to have it read "We strongly encourage you to upgrade to the latest version to continue receiving updates." ?

2022-04-08 16:48 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to version [version number] or abov
```suggestion
Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to the latest version to continue receiving updates. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 16:49 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to version [version number] or abov
```suggestion
Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to the latest version to continue receiving updates. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 16:51 UTC, mario-guerra commented on docs/policies/releases.md
> +-	Make updates to the legacy packages in the package manager. Use the following message and follow programming language instructions.
In that case what should we do for old Python releases to let people know that a package has been deprecated?

2022-04-08 16:52 UTC, mario-guerra commented on docs/policies/releases.md
> +TS/JS | Run the command `npm deprecate` which takes the package name and the deprecation message.
```suggestion
TS/JS | Run the relevant build pipeline.
```

2022-04-08 16:58 UTC, mario-guerra commented on docs/policies/releases.md
> +Python | Publish an update to the package after updating the README.
Okay, is there anything about this wording that should be changed?

2022-04-08 17:08 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, this package has been deprecated. A replacement package is available [package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly encourage you to upgrade to continue
```suggestion
Please note, this package has been deprecated. A replacement package is available <br>[package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly <br>encourage you to upgrade to continue receiving updates. See the <br>[Migration Guide](https://dummylink.com/) for guidance on upgrading. Refer to our <br>[deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 17:11 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, this package has been deprecated. A replacement package is available <br>[package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly <br>encourage you to upgrade to c
```suggestion
Please note, this package has been deprecated. A replacement package is available  [package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly  encourage you to upgrade to continue receiving updates. See the  [Migration Guide](https://dummylink.com/) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 17:13 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, this package has been deprecated. A replacement package is available  [package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly  encourage you to upgrade to continu
```suggestion
Please note, this package has been deprecated. A replacement package is available\ [package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly\ encourage you to upgrade to continue receiving updates. See the\ [Migration Guide](https://dummylink.com/) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 17:15 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, this package has been deprecated. A replacement package is available\ [package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly\ encourage you to upgrade to continu
```suggestion
Please note, this package has been deprecated. A replacement package is available
[package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly
encourage you to upgrade to continue receiving updates. See the
[Migration Guide](https://dummylink.com/) for guidance on upgrading. Refer to our 
[deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 17:16 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, this package has been deprecated. A replacement package is available\ [package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly\ encourage you to upgrade to continu
```suggestion
Please note, this package has been deprecated. A replacement package is available
[package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly
encourage you to upgrade to continue receiving updates. 
See the [Migration Guide](https://dummylink.com/) for guidance on upgrading. 
Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 17:17 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to the latest version to continue r
```suggestion
Please note, versions of this package with version numbers [version number] and below have been deprecated
as of [date-MM-YY]. We strongly encourage you to upgrade to the latest version to continue receiving updates.
Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 17:18 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, this package has been deprecated. A replacement package is available [package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly encourage you to upgrade to continue
```suggestion
Please note, this package has been deprecated. A replacement package is available
[package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly
encourage you to upgrade to continue receiving updates. 
See the [Migration Guide](https://dummylink.com/) for guidance on upgrading.
Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 17:20 UTC, mario-guerra commented on docs/policies/releases.md
> +Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to the latest version to continue r
```suggestion
Please note, versions of this package with version numbers [version number] and below have been 
deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to the latest version to 
continue receiving updates. 
Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-08 17:21 UTC, mario-guerra commented on docs/policies/releases.md
> +Samples in this repository use deprecated packages [list legacy package here]. We recommend that you get started using the new package here instead: [package name](https://dummylinktopackage.com/.
```suggestion
Samples in this repository use deprecated packages [list legacy package here]. We recommend
that you get started using the new package here instead: [package name](https://dummylinktopackage.com/.
```

2022-04-08 18:30 UTC, lmazuel commented on docs/policies/releases.md
> +Please note, versions of this package with version numbers [version number] and below have been deprecated as of [date-MM-YY]. We strongly encourage you to upgrade to version [version number] or abov
I'm fine with that wording :)

2022-04-08 18:32 UTC, lmazuel commented on docs/policies/releases.md
> +-	Make updates to the legacy packages in the package manager. Use the following message and follow programming language instructions.
You don't have a lot of flexibilty the way PyPI is designed. They will get a box that should check for newer version part of PyPI automatically:

![image](https://user-images.githubusercontent.com/1050156/162500872-529ce8c0-8155-4e88-975a-a7ed0df8a80e.png)

Honestly, I think for Python people this is enough, as old package are frozen in time anyway

2022-04-08 18:36 UTC, lmazuel commented on docs/policies/releases.md
> +Python | Publish an update to the package after updating the README.
If "the package" refers to the deprecated package where we didn't change a name, we can't publish an update. So we could word it maybe:
If the deprecated package is no longer in use (new version has a different name), publish an update to the deprecated package after updating the Readme

2022-04-11 19:23 UTC, mario-guerra commented on docs/policies/releases.md
> +-	Make updates to the legacy packages in the package manager. Use the following message and follow programming language instructions.
```suggestion
-	In the package managers that support updates to existing packages, update the legacy packages in the package manager to include a deprecation notice. Use the following message and follow programming language instructions.
```

2022-04-11 19:24 UTC, mario-guerra commented on docs/policies/releases.md
> +Python | Publish an update to the package after updating the README.
```suggestion
Python | If the deprecated package is no longer in use (new version has a different name), publish an update to the deprecated package after updating the README
```

2022-04-11 20:38 UTC, joshfree requested changes

2022-04-11 20:38 UTC, joshfree commented on docs/policies/releases.md
> +[package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly
Don't do these dummylinktopackage.com or dummylink.com variations.  Use a link to an asset we own and control.

2022-04-11 20:40 UTC, joshfree commented on docs/policies/releases.md
> +- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br>
1 year seems short.  Is this coming from a policy that can be linked to?

2022-04-11 20:42 UTC, mario-guerra commented on docs/policies/releases.md
> +[package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly
```suggestion
[package name](https://aka.ms/azsdk) as of [date-MM/YY]. We strongly
```

2022-04-11 20:44 UTC, mario-guerra commented on docs/policies/releases.md
> +See the [Migration Guide](https://dummylink.com/) for guidance on upgrading.
```suggestion
See the [Migration Guide](https://aka.ms/azsdk) for guidance on upgrading. 
```

2022-04-11 20:44 UTC, mario-guerra commented on docs/policies/releases.md
> +that you get started using the new package here instead: [package name](https://dummylinktopackage.com/.
```suggestion
that you get started using the new package here instead: [package name](https://aka.ms/azsdk).
```

2022-04-11 20:45 UTC, mario-guerra commented on docs/policies/releases.md
> +This document covers [library name] [package name](https://dummylinktopackage.com/).
```suggestion
This document covers [library name] [package name](https://aka.ms/azsdk).
```

2022-04-11 20:45 UTC, mario-guerra commented on docs/policies/releases.md
> +See [Migration Guide](https://dummylink.com/) for more details.
```suggestion
See [Migration Guide](https://aka.ms/azsdk) for more details.
```

2022-04-11 20:46 UTC, mario-guerra commented on docs/policies/releases.md
> +[package name](https://dummylinktopackage.com/) as of [date-MM/YY]. We strongly
```suggestion
[package name](https://aka.ms/azsdk) as of [date-MM/YY]. We strongly
```

2022-04-11 20:46 UTC, mario-guerra commented on docs/policies/releases.md
> +See the [Migration Guide](https://dummylink.com/) for guidance on upgrading.
```suggestion
See the [Migration Guide](https://aka.ms/azsdk) for guidance on upgrading.
```

2022-04-11 20:51 UTC, mario-guerra commented on docs/policies/releases.md
> +- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br>
```suggestion
- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br> You don’t have to proactively fix anything else, but a customer calling for support should be able to get it. Refer to our [support policy page](https://azure.github.io/azure-sdk/policies_support.html) for more details.

2022-04-11 20:56 UTC, mario-guerra commented on docs/policies/releases.md
> +- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br>
```suggestion
- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br> You don’t have to proactively fix anything else, but a customer calling for support should be able to get it. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-11 22:39 UTC, lmazuel approved these changes

2022-04-11 23:00 UTC, mario-guerra commented on docs/policies/releases.md
> +- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br>
```suggestion
- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br> You don’t have to proactively fix anything else, but a customer calling for support should be able to get it. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details
```

2022-04-11 23:03 UTC, mario-guerra commented on docs/policies/releases.md
> +- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br>
```suggestion
- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br> You don’t have to proactively fix anything else, but a customer calling for support should be able to get it. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details
```

2022-04-11 23:05 UTC, mario-guerra commented on docs/policies/releases.md
> +- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br>
```suggestion
- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br> You don’t have to proactively fix anything else, but a customer calling for support should be able to get it. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.
```

2022-04-11 23:07 UTC, mario-guerra commented on docs/policies/releases.md
> +- Ensure you have the infrastructure in place to build and ship fixes for the legacy libraries for the next 3 years.<br> You will need to ship security and critical bug fixes for the first year.<br>
Added link to our support policy.

2022-04-13 17:58 UTC, joshfree commented on docs/policies/releases.md
> +Java | Update the project description in the POM file to include the deprecation message. Publish Update.
The instructions for Java should be similar to the text for Python.  We want to point developers to the new T2 package, which almost definitely has a new name.

2022-04-13 18:05 UTC, mario-guerra commented on docs/policies/releases.md
> +Java | Update the project description in the POM file to include the deprecation message. Publish Update.
```suggestion
Java | If the deprecated package is no longer in use (new version has a different name), publish an update to the deprecated package after updating the README
```

2022-04-13 18:36 UTC, joshfree approved these changes

2022-04-13 18:36 UTC, mario-guerra commented
#sign-off

2022-04-13 18:37 UTC, mario-guerra commented
Sign off received from all the language leads, committing this PR.

2022-04-13 18:37 UTC, merged

2022-06-14 23:50 UTC, weshaggard commented on docs/policies/releases.md
> +Language|Instructions
@mario-guerra This MD table isn't correctly formatted. You need to add `|` and the beginning and ending of the each line.