Added first draft for event handling guidelines for Android.
Azure/azure-sdk pull request #4351
Opened 2022-05-25 02:41 UTC by vcolin7

Based on previous discussions, I created a first draft for the adding event handling guidelines for Android, similar to [the effort for iOS](https://github.com/Azure/azure-sdk/pull/4229). I also [opened a PR](https://github.com/Azure/azure-sdk-for-android/pull/1119) containing the `azure-core` classes and interfaces mentioned in this draft.

2022-05-25 05:56 UTC, srnagar commented on docs/android/design.md
> +Android applications commonly need to react to events from the UI or service. The following guidelines apply to SDKs that expose events to the customer.
SDKs -> client libraries

2022-05-25 05:56 UTC, srnagar commented on docs/android/design.md
> +Android applications commonly need to react to events from the UI or service. The following guidelines apply to SDKs that expose events to the customer.
"that expose events to the customer." -> "that provide APIs to handle events".

2022-05-25 05:56 UTC, srnagar commented on docs/android/design.md
> +##### Handlers
```suggestion
##### Event Handlers
```

2022-05-25 05:56 UTC, srnagar commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-unicast-handler" %} declare unicast event handlers as functional interfaces that use the `@FunctionalInterface` annotation.
`@FunctionalInterface` is available for Java 8+ versions. Android libraries targeting lower versions of Java will not be able to use this annotation.

2022-05-25 05:56 UTC, srnagar commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-unicast-handler" %} declare unicast event handlers as functional interfaces that use the `@FunctionalInterface` annotation.
We should also provide guidance on when to use unicast vs multicast handlers. While we lean towards multicast handlers to be the default, what are the scenarios when unicast is desirable?

2022-05-25 05:56 UTC, srnagar commented on docs/android/design.md
> +}
Creating a new type is not necessary.

2022-05-25 05:56 UTC, srnagar commented on docs/android/design.md
> +    public void handleMessagingEvent(MessagingEvent event) {
Doesn't this also require the eventType?

2022-05-25 05:56 UTC, srnagar commented on docs/android/design.md
> +If you need to provide additional details about an event to a handler, {% include requirement/MUST id="android-event-with-properties %} do so by declaring a class that extends from `Event` in `azure-
`MUST` should be at the beginning

2022-05-25 05:56 UTC, srnagar commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-multicast" %} expose multicast event handlers using the `MulticastEventCollection` type from `azure-core`. This type contains an `addEventHandler` method
`MulticastEventCollection` should not be directly visible to the customer. It must only be used by library developers. So, we have to rephrase this "expose multicast event handlers using `MulticastEventCollection`".

2022-05-26 04:45 UTC, vcolin7 commented on docs/android/design.md
> +    public void handleMessagingEvent(MessagingEvent event) {
I wrote two overloads for this in `MulticastEventCollection`: `handleEvent(T eventType, E event)` and `handleEvent(E event)`. The first one is the original method and the second one calls it after extracting the event type from `event`, but only if the object is a subclass of `Event`, else it throws. We could remove the second overload and simply work with the first one I mentioned if you think it's better for now. I thought that since `eventType` is already a member of `Event`, some users might think it's unnecessary to extract it manually to call `handleEvent()`.

Also, if you're thinking: "Is there any occasion where we won't pass an instance `Event` to the handler?", I thought not all events might carry details other than the type, so would it not feel unnecessary to box the type in `Event` for these cases? In such a case, I guess we could have a method to handle an event that only receives its type? I don't know, I need to ponder a bit more on this.

2022-05-26 04:48 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-unicast-handler" %} declare unicast event handlers as functional interfaces that use the `@FunctionalInterface` annotation.
Agreed, I think we could do something like what we do for optional arguments, where if there will be just a finite number of handlers and events you can follow these semantics but if will be more than X or it can grow we tell developers to go with multicast from the get go. What do you think?

2022-05-30 22:03 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-unicast-handler" %} declare unicast event handlers as functional interfaces that use the `@FunctionalInterface` annotation.
I think that will lead to confused APIs where end users will not have certainty where to look for the event handling functionality. I would propose that by default always have multicast and have unicast be on a case-by-case approval basis.

2022-06-07 08:09 UTC, vcolin7 commented on docs/android/design.md
> +public void onMessagingEvent(MessagingEventType eventType, MessagingEvent event) {
Should we instead use this nomenclature? @JonathanGiles @srnagar 
```suggestion
public void handleMessagingEvent(MessagingEventType eventType, MessagingEvent event) {
```

2022-06-08 12:50 UTC, Lillithlilly approved these changes

2022-06-08 16:38 UTC, tjprescott commented on docs/android/design.md
> +}
Are these examples of extra properties or is boilerplate that every specific event needs?  If everything needs it, can this live in the base class?

2022-06-08 16:41 UTC, tjprescott commented on docs/android/design.md
> +```
Per our discussion, I'd recommend the second option by the MUST and don't allow the first.

2022-06-15 22:26 UTC, vcolin7 commented on docs/android/design.md
> +}
We will remove the base `Event` class but encourage devs to bundle event details together in a class such as this. They will still be able to pass things like `String` directly to a handler

2022-06-15 22:27 UTC, vcolin7 commented on docs/android/design.md
> +```
After talking to the architects, we will be going with the first approach only as they feel it's more idiomatic.

2022-06-20 01:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MAY id="android-event-handler-mutable" %} mutate individual event handlers after client instantiation, unlike most client configuration which is required to be immutable.
```suggestion
{% include requirement/MAY id="android-event-handler-mutable" %} allow users to add and remove individual event handlers after client instantiation through the `add` and `remove` methods detailed below. This is not considered to be mutating the state of the client.
```

2022-06-20 01:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-handler-collection" %} use Azure Core's `EventHandlerCollection` internally to keep track of registered event handlers and their associations with differ
This isn't strictly necessary. It is recommended though.. I would change it to ensure that the given code sample demonstrates how this is to be used.

2022-06-20 01:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-types" %} declare event types to associate event handlers with as package private client constants of the type `String`.
We should move this guidance (and the previous one) from the API design documentation and into the implementation documentation.

2022-06-20 01:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-handler-registration" %} register event handlers on clients via methods whose names start with the `addOn` prefix and end with the `Handler` suffix.
I'm not convinced the `On` adds much value, e.g. is `addOnKeyTypedHandler` better than `addKeyTypedHandler`? The `On` makes more sense if we didn't enforce the `Handler` suffix - `addOnKeyTyped` requires the `On`, because we've dropped `Handler`. What is more useful for developers? We have:

* `addOnKeyTypedHandler`
* `addKeyTypedHandler`
* `addOnKeyTyped`

2022-06-20 01:37 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-handler-registration-arguments" %} have said methods take one argument that is an implementation of the `EventHandler` interface from Azure Core. This ar
```suggestion
{% include requirement/MUST id="android-event-handler-registration-arguments" %} define event handler methods as taking a single argument of type `EventHandler` (from Azure Core). This argument must be named `handler`.
```

2022-08-09 04:32 UTC, Petermarcu commented
@vcolin7  what are the next steps here to get this merged?

2022-08-09 15:54 UTC, vcolin7 commented
> @vcolin7 what are the next steps here to get this merged?

@Petermarcu I need to apply latest feedback by Jonathan and Srikanta and have them review again. We can do that this week.

2022-10-14 20:44 UTC, vcolin7 commented
Keep open.

2023-01-05 23:08 UTC, tjprescott commented
Stop closing this.

2023-02-28 08:33 UTC, vcolin7 commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-handler-registration" %} register event handlers on clients via methods whose names start with the `addOn` prefix and end with the `Handler` suffix.
When I originally wrote this I thought it would be good to be overtly explicit with the names to avoid some awkward names. For example, if the event method in a client would be called `onClick()`, I would rather have `addOnClickHandler()` than `addClickHandler()` or `addOnClick()`. I get that for methods that use the past form of a verb that might not be necessary, with things like `onClick()` or `onCreate()` being a standard for Android this felt like the right thing to do. We could drop the `Handler` suffix for something like `addOnKeyTyped()` but I am not sure if it's better to just have a single guidance than two different ones based on some condition.

2023-03-02 20:39 UTC, JonathanGiles requested changes
Additional feedback - please keep the iterations coming!

2023-03-02 20:39 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MAY id="android-event-handler-mutable" %} allow users to add and remove individual event handlers after client instantiation through the `add` and `remove` methods detailed bel
We should consider the builder- vs client-level configuration of event handlers. It is easy to understand why client-level API to add / remove / set event handlers is good, but there exists prior art in our own libraries where we set the event handlers on the builder. For example, the Event Hubs processor APIs have process* methods on the builder, because this forms a fundamental aspect of the processor, and it could be argued that it would be counter-intuitive to use a builder to create a processor, only to configure its fundamental functionality in the subsequently constructed processor client.

The wider question is - do we allow this, and what are the conditions for allowing it? Then, if it is allowed, what is the naming pattern that we use for builder-based event handlers versus client-based event handlers?

2023-03-02 20:39 UTC, JonathanGiles commented on docs/android/design.md
> +{% include requirement/MUST id="android-event-handler-registration" %} register event handlers on clients via methods whose names start with the `addOn` prefix and end with the `Handler` suffix.
I don't strongly hold an opinion on this - the main thing is the consistency that we want to derive from it. `addOn*Handler` is fine with me, but I'm open to discussion on shortening this in various ways.

2023-03-02 20:39 UTC, JonathanGiles commented on docs/android/design.md
> +}
Because all events are generated by us (and never by users), we should expect that an `*Event` is `@Immutable`. So, no setters should be shown, and rather we should have a ctor taking all required parameters.

2023-03-02 20:39 UTC, JonathanGiles commented on docs/android/design.md
> +```
It took me a few reads of the text to fully understand what was intended, even though I remember discussing it a long time ago. "MAY instead provide other types of objects to event handlers when grouping event details together is not necessary" might be better written as "MAY use existing types, rather than a new Event type, when an existing type provides all necessary data necessary to the user. Note that this prevents future growth to provide additional information to the user, so do not do this without much consideration."

2023-03-02 20:39 UTC, JonathanGiles commented on docs/android/design.md
> +    public void handle(String timestamp) {
`timestamp` as the parameter name is probably not the best choice - otherwise you should probably change the EventHandler to be Long rather than String. If you want to keep it as String, lets find a better parameter name, e.g. 'filename', 'message', 'userInput', 'alertMessage', etc.

2023-03-07 01:08 UTC, vcolin7 commented on docs/android/design.md
> +public void onMessagingEvent(MessagingEventType eventType, MessagingEvent event) {
@JonathanGiles Here's an old question I had that could play a role on how we name the methods we talk about [here](https://github.com/Azure/azure-sdk/pull/4351#discussion_r901193360).

2023-05-12 22:41 UTC, vcolin7 commented
Will work on this next week.

2023-07-21 16:41 UTC, tjprescott commented
@vcolin7 what remains on this? cc/ @JonathanGiles

2023-09-29 08:33 UTC, closed without merging