Update User-Agent guideline
Azure/azure-sdk pull request #5196
Opened 2022-12-01 23:57 UTC by joheredi

Updating the General Guidelines with the outcome of the Architecture Board discussion on User-Agent string consistency across languages.

Arch Board issue: https://github.com/Azure/azure-sdk/issues/5110

2022-12-03 00:12 UTC, JeffreyRichter approved these changes

2022-12-05 20:32 UTC, JonathanGiles requested changes
One nit, one Java-specific typo that should be fixed.

2022-12-05 20:32 UTC, JonathanGiles commented on docs/general/azurecore.md
> +{% include requirement/MUST id="azurecore-http-telemetry-useragent" %} send telemetry information in the [User-Agent header]
```suggestion
{% include requirement/MUST id="azurecore-http-telemetry-useragent" %} send telemetry information in the [User-Agent header].
```

2022-12-05 20:32 UTC, JonathanGiles commented on docs/general/azurecore.md
> +- (Java) `AzCopy/10.0.4-Preview azsdk-java-storage.datalake/12.0.0 azsdk-java-storage.blobs/12.0.0 azsdk-java-core/11.0.0 (Java/1.8.0_45; Macintosh; Intel Mac OS X 10_10; rv:33.0)`
```suggestion
- (Java) `AzCopy/10.0.4-Preview azsdk-java-storage-datalake/12.0.0 azsdk-java-storage-blobs/12.0.0 azsdk-java-core/11.0.0 (Java/1.8.0_45; Macintosh; Intel Mac OS X 10_10; rv:33.0)`
```

2022-12-10 00:36 UTC, KrzysztofCwalina commented on docs/general/azurecore.md
> +{% include requirement/MUST id="azurecore-http-telemetry-useragent-stacking" %} extend the user agent to list all `client wrapping` dependencies, sorting them from outermost to innermost.
I would add an example here. Without it, I suspect many readers will not know what 'client wrapping' means

2022-12-10 00:36 UTC, KrzysztofCwalina commented on docs/general/azurecore.md
> +{% include requirement/SHOULD id="azurecore-http-telemetry-useragent-stacking-core" %} include core dependencies in the user agent.
what are "core dependencies"? i.e. we need to be more precises such that a reader can actually implement this guideline without having to ask us how.

2023-01-11 21:34 UTC, merged