Update CSV files for package deprecation
Azure/azure-sdk pull request #5850
Opened 2023-03-31 07:49 UTC by johnemmanuelm

2023-03-31 19:18 UTC, weshaggard commented on _data/releases/latest/js-packages.csv
> +"@azure/arm-storageimportexport","2.1.0","","Resource Management - Storage Import/Export","Storage","https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/storageimportexport/arm-storageimportexpor
The replacement package and guide isn't correct here. It looks like you copied from go.

2023-03-31 19:19 UTC, weshaggard requested changes
The replacement package and mitigation links need to be fixed.

2023-04-04 15:33 UTC, mario-guerra requested changes
Hi, for Python, .NET, JS, and Java, the 'Replace' field should just be the package name that shows up in the language package manager, not the sdk repo path.

2023-04-04 17:23 UTC, mario-guerra approved these changes

2023-04-04 17:44 UTC, weshaggard commented on _data/releases/latest/js-packages.csv
> +"@azure/arm-storageimportexport","2.1.0","","Resource Management - Storage Import/Export","Storage","https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/storageimportexport/arm-storageimportexpor
Isn't the replacement package the same as the original package here?

2023-04-04 17:52 UTC, johnemmanuelm commented on _data/releases/latest/js-packages.csv
> +"@azure/arm-storageimportexport","2.1.0","","Resource Management - Storage Import/Export","Storage","https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/storageimportexport/arm-storageimportexpor
Fixed

2023-04-04 17:57 UTC, weshaggard approved these changes

2023-04-04 17:57 UTC, merged