Ronniegeraghty inventory updates2
Azure/azure-sdk pull request #6264
Opened 2023-06-10 01:34 UTC by ronniegeraghty

Adds exceptions for IoT libraries and Updates IoT Libraries

2023-06-10 02:53 UTC, ahsonkhan requested changes
Out of curiosity, what is motivating this change (if you could share some context)?

2023-06-10 02:53 UTC, ahsonkhan commented on eng/scripts/inventory-dashboard/data-and-rules/exceptionsList.json
> +    },
What about C++?

2023-06-10 02:54 UTC, ahsonkhan submitted a review, later dismissed
Accidentally clicked "Request changes." Overriding.

2023-08-12 06:05 UTC, czubair approved these changes

2023-08-14 16:50 UTC, merged