Add PWSH to devcontainer
Azure/azure-sdk pull request #7202
Opened 2024-02-07 22:58 UTC by weshaggard

2024-02-07 23:59 UTC, weshaggard commented on .devcontainer/Dockerfile
> +FROM mcr.microsoft.com/devcontainers/ruby:2.7-buster
```suggestion
FROM ruby:2.7.4-buster
```

2024-02-08 00:09 UTC, heaths requested changes

2024-02-08 00:09 UTC, heaths commented on .devcontainer/devcontainer.json
> +        "powershell": "latest"
Where'd you see this document as such? According to https://github.com/devcontainers/features/tree/main/src/powershell, it should be:
```suggestion
        "ghcr.io/devcontainers/features/powershell:1": {}
```

2024-02-08 00:30 UTC, weshaggard commented on .devcontainer/devcontainer.json
> +        "powershell": "latest"
Found it at https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/powershell.md however if I click through I get to https://github.com/devcontainers/features/tree/main/src/powershell which is what you are suggesting.

2024-02-08 00:41 UTC, heaths approved these changes

2024-02-08 00:41 UTC, merged