Update Rust guidelines for options builder pattern
Azure/azure-sdk pull request #7587
Opened 2024-05-21 22:31 UTC by heaths

2024-05-21 22:33 UTC, heaths commented
Combines https://gist.github.com/heaths/5f06f7d221f87ee44d6e2c5e7b23e104 with https://github.com/heaths/azure-sdk-for-rust-proto/pull/10/files. I'll update the prototype repo to probably just have this one prototype and we can have another SDK architect meeting, if that works for you all.

/cc @RickWinter @JeffreyRichter @LarryOsterman @jhendrixMSFT

2024-05-21 22:33 UTC, heaths commented
I'm going to update `implementation.md` before marking this ready.

2024-05-22 00:05 UTC, JeffreyRichter submitted a review, later dismissed

2024-05-22 00:08 UTC, jhendrixMSFT commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
Somewhat orthogonal to this PR but, what will the return type be for operations that don't return a model (e.g. 204 no content)?

2024-05-22 00:12 UTC, JeffreyRichter commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
I think the ONLY operations that return 204 is DELETE.
Everything else returns 200 with a {} body so that new properties can be added in the future in a non-breaking way.
We don't let 204 response change to 200 in the future as this could be breaking.

2024-05-22 14:00 UTC, jhendrixMSFT commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
Let me ask the question a different way. For the following tsp:

`putKnownValue(@body body: DaysOfWeekExtensibleEnum): void;`

What's the modeled return type in Rust?

2024-05-22 16:25 UTC, LarryOsterman commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
> Let me ask the question a different way. For the following tsp:
> 
> `putKnownValue(@body body: DaysOfWeekExtensibleEnum): void;`
> 
> What's the method return type in Rust?

If you don't have a `-> <type>`, the return type is void.

2024-05-22 16:35 UTC, LarryOsterman requested changes
Looks good, I only have two nits about ensuring that the `builder()` method is static.

2024-05-22 16:35 UTC, LarryOsterman commented on docs/rust/introduction.md
> +{% include requirement/MUST id="rust-client-configuration-builder-methods-build" %} define a `build(&self)` method that borrows self and returns the associated client options struct. This allows crea
QQ: Do we want to make this a SHOULD instead of a MUST to give client authors the option to consume self on the `build` method? Possibly with a caveat that they should consult the architecture board if they want to violate the SHOULD?

2024-05-22 16:35 UTC, LarryOsterman commented on docs/rust/introduction.md
> +{% include requirement/MUST id="rust-client-methods-configuration-name" %} define a client method options struct with the same as the client method name + "MethodOptions" e.g., a `set_secret` takes a
Possibly add text about requiring the options structure even if the service method doesn't currently take options?

If the client options are empty, do customers need to provide builders for those options?

2024-05-22 16:35 UTC, LarryOsterman commented on docs/rust/introduction.md
> +{% include requirement/MUST id="rust-client-methods-configuration-builder-function" %} define a `builder()` function that returns an instance of its associated builder as defined below.
```suggestion
{% include requirement/MUST id="rust-client-methods-configuration-builder-function" %} define a static `builder()` function that returns an instance of its associated builder as defined below.
```

2024-05-22 16:37 UTC, LarryOsterman commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
Good point: We probably want to return an `azure_core::Result<T>` for all service methods. But then the question is: Can we specialize `azure_core::Result` on `void`?

2024-05-22 16:52 UTC, JeffreyRichter commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
Larry's suggestion is good, but I worry that changing void to non-void someday would be breaking when that day comes. Methods that invoke a non-LRO HTTP DELETE should always return 204/void. But any other method should probably return a structure which may have no fields in it today but may get fields in it tomorrow. This would be the most conservative & less chance of breaking in the future approach.

2024-05-22 16:54 UTC, JeffreyRichter commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
I think putKnownValue(@body body: DaysOfWeekExtensibleEnum): void; may also not be valid from an Azure perspective. In REST, a PUT should ALWAYS have a response body.

2024-05-22 17:05 UTC, LarryOsterman commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
? Why would PUT always have a response body? I fully understand why it would have a request body, but why would it also have a response body, especially if the response is a 200?

2024-05-22 17:24 UTC, LarryOsterman commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
To be clear: I think the idea of having an empty `T` type isn't a bad idea for service methods which currently don't have a defined return model, similar to the service request methods having a T value.

But I worry that customers will be confused at seeing service methods returning an empty model type (they won't realize this is an issue for service methods because the request options is hidden behind a Some().

Also it's going to be important that services that change from "not returning anything" to "return something" ensure that the data in "something" not be something the client must make a decision about. IMHO, it's a breaking change to add a "something" that is not purely informational.

2024-05-22 17:48 UTC, jhendrixMSFT commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
The empty `T` response type is the approach we use in Go, and it's worked well. I do agree though that it muddies the waters. i.e. it's not clear from the method sig if the `T` is useful or not, you have to look at its definition. And, if it changes in the future, you won't know it.

2024-05-22 17:48 UTC, JeffreyRichter commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
First, any operation that returns 200 is saying that the operation succeeded and there is a response body. 204 indicates succeeded with no response body. 
Second, with REST, PUT means Create or Replace and the request body is the resource value being created/replaced. If the response returns 200 (as it always should for a non-LRO PUT), the response body is the same as the request body (potentially augmented). The response body is the "proof" of what got persisted by the service and frequently, the service adds its own additional properties to the response (the augmentation I speak of). For example, a request may not include some property and then the service has a default for this property, the value chosen by the service WILL BE returned in the response.

2024-05-22 18:00 UTC, jhendrixMSFT commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
If you imagine a Venn diagram with two circles, one for what you can express in tsp, and the other what's considered valid for an Azure service (or REST for that matter), the two don't overlap 100%. I suppose there's also a third circle for unbranded codegen, but let's ignore that for now.

The operation I cited earlier is legal tsp, and that pattern is littered throughout the cadl-ranch test suite. e.g. a lot of tests come in pairs like this.
```
getFoo(): Foo
putFoo(body: Foo): void
```

2024-05-22 18:17 UTC, JeffreyRichter commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
OK, so then I agree with what Larry said above: If you don't have a -> <type>, the return type is void.
I don't know if Rust lets you do Result<void>. C# doesn't and so there was a Result base class (for void) and a Result<T> derived class (for non-void).

2024-05-22 18:23 UTC, jhendrixMSFT commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
The method return can't be `void` as that precludes the ability to communicate if the HTTP operation failed. Should it be `azure_core::Error`? Like this:
```rust
pub async fn put_known_value(&self, _body: DaysOfWeekExtensibleEnum, _options: Option<&PutKnownValueMethodOptions>) -> azure_core::Error { ... }
```

2024-05-22 18:24 UTC, jhendrixMSFT commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
No that doesn't work. But I think `azure_core::Error` needs to be in there somewhere?

2024-05-22 18:35 UTC, jhendrixMSFT commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
Ah hah! Yep that works.

2024-05-22 21:00 UTC, heaths commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
Yes, you should use `azure_core::Result<()>`. That's the idiomatic approach.

However, this does mean we don't get headers or anything of a raw response. Perhaps we need to rethink this exact case, but go with `Result<()>` for now. Perhaps we need just a `Response`. Thoughts?

2024-05-22 21:01 UTC, heaths commented on docs/rust/introduction.md
> +{% include requirement/MUST id="rust-client-configuration-builder-methods-build" %} define a `build(&self)` method that borrows self and returns the associated client options struct. This allows crea
We treat these as exceptions. They can always ask for exceptions, but guidelines typically take a more strict approach. I know this is what both @JeffreyRichter and Krzysztof have told me in the past as well, but Jeffrey can reopen if he disagrees in this case.

2024-05-22 21:02 UTC, heaths commented on docs/rust/introduction.md
> +{% include requirement/MUST id="rust-client-methods-configuration-builder-function" %} define a `builder()` function that returns an instance of its associated builder as defined below.
"static" isn't idiomatic to rust, hence the word "function" at the end. Perhaps that's too subtle though, especially for those unfamiliar with rust?

2024-05-22 21:02 UTC, jhendrixMSFT commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
Agreed that we need to sort headers etc. Can we do that separate from this?

2024-05-22 22:21 UTC, LarryOsterman commented on docs/rust/introduction.md
> +{% include requirement/MUST id="rust-client-methods-configuration-builder-function" %} define a `builder()` function that returns an instance of its associated builder as defined below.
Looking at that page, it appears that the idiomatic Rust language to distinguish between a method with a self parameter and a method without a self parameter is to call the second thing an "[associated function](https://doc.rust-lang.org/book/ch05-03-method-syntax.html#associated-functions)" although it's somewhat confusing because it says that associated functions are *all* the functions in a class `impl` block, whether they have a `self` parameter or not.

Maybe instead of saying "static", we say "associated builder() function without a self parameter"? But it would be nice to have a shorter phrasing for that.

FWIW, [this](https://rustlabs.github.io/docs/rust101/staticmethodofstructs/) seems to use the term "static method". But I don't know how authoritative this is.

2024-05-29 23:59 UTC, heaths commented on docs/rust/introduction.md
> +    ) -> azure_core::Result<Response<KeyVaultSecret>> {
Yeah. We can think separately about it.

Maybe it just ends up being `Result<Response<()>>`. Honestly, that feels more idiomatic since the unit type `()` represents "no type". In fact, any `fn main()` that doesn't return a `Result<T, E>` actually returns `()` implicitly.

@cataggar @demoray @jamesbell what do you think of this for methods that don't return a model?

2024-05-30 00:00 UTC, heaths commented on docs/rust/introduction.md
> +{% include requirement/MUST id="rust-client-methods-configuration-builder-function" %} define a `builder()` function that returns an instance of its associated builder as defined below.
Yeah, concise is better. We could let `static` stand. Pedantry is reserved for those with too much time on their hands. 😉

2024-06-05 00:01 UTC, heaths commented
Draft status has been removed

2024-06-05 18:43 UTC, merged